name = "fuseit-wordle"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend/build/web"

[[d1_databases]]
binding = "DB"
database_name = "fuseit-word-db"
database_id = "fa9b721a-9aba-4891-9869-0d72111cbf52"
