name = "fuseit-wordle"
compatibility_date = "2024-01-01"
pages_build_output_dir = "frontend/build/web"

[[d1_databases]]
binding = "DB"
database_name = "fuseit-wordle-db"
database_id = "374b3d54-0441-4f18-9282-5fe9f4020534"
