// 365 themes for Span.IT — one per day of the year
// Each theme has a display name and Datamuse API topics string
export const THEMES = [
  // January (31)
  { name: 'Ocean Life',             topics: 'ocean,sea,marine' },
  { name: 'Space Exploration',      topics: 'space,astronomy,cosmos' },
  { name: 'Cooking & Food',         topics: 'cooking,food,cuisine' },
  { name: 'Ancient History',        topics: 'ancient,history,civilization' },
  { name: 'Music',                  topics: 'music,melody,rhythm' },
  { name: 'Weather & Climate',      topics: 'weather,climate,atmosphere' },
  { name: 'Sports',                 topics: 'sports,athletics,competition' },
  { name: 'Technology',             topics: 'technology,computers,software' },
  { name: 'Animals',                topics: 'animals,wildlife,creatures' },
  { name: 'Architecture',           topics: 'architecture,buildings,construction' },
  { name: 'Human Body',             topics: 'anatomy,body,medicine' },
  { name: 'Travel & Adventure',     topics: 'travel,adventure,exploration' },
  { name: 'Art & Creativity',       topics: 'art,painting,creativity' },
  { name: 'Science',                topics: 'science,chemistry,physics' },
  { name: 'Mythology',              topics: 'mythology,legends,gods' },
  { name: 'Fashion & Style',        topics: 'fashion,clothing,style' },
  { name: 'Gardening & Plants',     topics: 'plants,gardening,nature' },
  { name: 'Film & Cinema',          topics: 'film,cinema,movies' },
  { name: 'Mathematics',            topics: 'mathematics,geometry,numbers' },
  { name: 'Languages & Words',      topics: 'language,linguistics,words' },
  { name: 'Forests & Trees',        topics: 'forest,trees,woodland' },
  { name: 'Insects & Bugs',         topics: 'insects,bugs,entomology' },
  { name: 'Emotions & Feelings',    topics: 'emotions,feelings,psychology' },
  { name: 'Geography',              topics: 'geography,countries,continents' },
  { name: 'Dinosaurs',              topics: 'dinosaurs,prehistoric,fossils' },
  { name: 'Farming & Agriculture',  topics: 'farming,agriculture,crops' },
  { name: 'Medicine & Health',      topics: 'medicine,health,healing' },
  { name: 'Superheroes',            topics: 'superheroes,comics,powers' },
  { name: 'Astronomy',              topics: 'stars,planets,telescope' },
  { name: 'Folklore & Legends',     topics: 'folklore,legends,myths' },
  { name: 'Winter & Snow',          topics: 'winter,snow,cold' },
  // February (28)
  { name: 'Love & Romance',         topics: 'love,romance,relationships' },
  { name: 'Chocolate & Sweets',     topics: 'chocolate,sweets,candy' },
  { name: 'Birds',                  topics: 'birds,avian,feathers' },
  { name: 'Oceans & Seas',          topics: 'oceans,seas,tides' },
  { name: 'Volcanoes & Geology',    topics: 'volcanoes,geology,rocks' },
  { name: 'Photography',            topics: 'photography,camera,images' },
  { name: 'Dance & Movement',       topics: 'dance,movement,choreography' },
  { name: 'Reptiles',               topics: 'reptiles,lizards,snakes' },
  { name: 'Bread & Baking',         topics: 'bread,baking,pastry' },
  { name: 'Castles & Fortresses',   topics: 'castles,fortresses,medieval' },
  { name: 'Clouds & Sky',           topics: 'clouds,sky,atmosphere' },
  { name: 'Robots & AI',            topics: 'robots,artificial intelligence,automation' },
  { name: 'Gems & Minerals',        topics: 'gems,minerals,crystals' },
  { name: 'Theatre & Drama',        topics: 'theatre,drama,performance' },
  { name: 'Deserts',                topics: 'desert,sand,arid' },
  { name: 'Fishing',                topics: 'fishing,angling,fish' },
  { name: 'Horses & Riding',        topics: 'horses,riding,equestrian' },
  { name: 'Bridges & Engineering',  topics: 'bridges,engineering,structures' },
  { name: 'Cheese & Dairy',         topics: 'cheese,dairy,milk' },
  { name: 'Caves & Underground',    topics: 'caves,underground,spelunking' },
  { name: 'Yoga & Meditation',      topics: 'yoga,meditation,mindfulness' },
  { name: 'Trains & Railways',      topics: 'trains,railways,locomotives' },
  { name: 'Flowers',                topics: 'flowers,blooms,petals' },
  { name: 'Puzzles & Games',        topics: 'puzzles,games,riddles' },
  { name: 'Camping & Outdoors',     topics: 'camping,outdoors,hiking' },
  { name: 'Sharks',                 topics: 'sharks,predators,ocean' },
  { name: 'Colours & Pigments',     topics: 'colours,pigments,hues' },
  { name: 'Clocks & Time',          topics: 'clocks,time,horology' },
  // March (31)
  { name: 'Spring & Renewal',       topics: 'spring,renewal,growth' },
  { name: 'Frogs & Amphibians',     topics: 'frogs,amphibians,wetlands' },
  { name: 'Sailing & Ships',        topics: 'sailing,ships,nautical' },
  { name: 'Cheese Making',          topics: 'fermentation,cheese,culture' },
  { name: 'Rainforests',            topics: 'rainforest,tropical,jungle' },
  { name: 'Cycling',                topics: 'cycling,bicycle,racing' },
  { name: 'Pottery & Ceramics',     topics: 'pottery,ceramics,clay' },
  { name: 'Storms & Lightning',     topics: 'storms,lightning,thunder' },
  { name: 'Cats',                   topics: 'cats,felines,kittens' },
  { name: 'Dogs',                   topics: 'dogs,canines,puppies' },
  { name: 'Bread & Grains',         topics: 'bread,grains,wheat' },
  { name: 'Volcanoes',              topics: 'volcanoes,lava,eruption' },
  { name: 'Martial Arts',           topics: 'martial arts,combat,fighting' },
  { name: 'Butterflies & Moths',    topics: 'butterflies,moths,insects' },
  { name: 'Cheese & Wine',          topics: 'wine,grapes,vineyard' },
  { name: 'Robots',                 topics: 'robots,machines,automation' },
  { name: 'Coral Reefs',            topics: 'coral,reef,marine' },
  { name: 'Hiking & Mountains',     topics: 'hiking,mountains,trails' },
  { name: 'Bees & Honey',           topics: 'bees,honey,pollination' },
  { name: 'Libraries & Books',      topics: 'libraries,books,reading' },
  { name: 'Submarines',             topics: 'submarines,underwater,navy' },
  { name: 'Spices & Herbs',         topics: 'spices,herbs,flavors' },
  { name: 'Archaeology',            topics: 'archaeology,excavation,artifacts' },
  { name: 'Surfing',                topics: 'surfing,waves,beach' },
  { name: 'Mushrooms & Fungi',      topics: 'mushrooms,fungi,spores' },
  { name: 'Astronomy & Stars',      topics: 'astronomy,stars,constellations' },
  { name: 'Knitting & Weaving',     topics: 'knitting,weaving,textiles' },
  { name: 'Frogs',                  topics: 'frogs,toads,amphibians' },
  { name: 'Cheese',                 topics: 'cheese,dairy,curd' },
  { name: 'Kites & Wind',           topics: 'kites,wind,flying' },
  { name: 'Eggs & Hatching',        topics: 'eggs,hatching,birds' },
  // April (30)
  { name: 'Rain & Puddles',         topics: 'rain,puddles,water' },
  { name: 'Frogs & Ponds',          topics: 'ponds,frogs,wetlands' },
  { name: 'Gardening',              topics: 'gardening,seeds,soil' },
  { name: 'Chocolate',              topics: 'chocolate,cocoa,sweets' },
  { name: 'Astronomy',              topics: 'planets,moons,orbits' },
  { name: 'Painting & Colours',     topics: 'painting,colours,canvas' },
  { name: 'Snakes',                 topics: 'snakes,reptiles,venom' },
  { name: 'Bridges',                topics: 'bridges,spans,engineering' },
  { name: 'Cheese & Crackers',      topics: 'crackers,snacks,cheese' },
  { name: 'Clouds',                 topics: 'clouds,cumulus,stratus' },
  { name: 'Origami',                topics: 'origami,paper,folding' },
  { name: 'Whales',                 topics: 'whales,cetaceans,ocean' },
  { name: 'Bread',                  topics: 'bread,loaves,yeast' },
  { name: 'Castles',                topics: 'castles,towers,moats' },
  { name: 'Butterflies',            topics: 'butterflies,wings,metamorphosis' },
  { name: 'Sailing',                topics: 'sailing,boats,wind' },
  { name: 'Volcanoes & Lava',       topics: 'lava,magma,eruption' },
  { name: 'Yoga',                   topics: 'yoga,poses,breathing' },
  { name: 'Trains',                 topics: 'trains,stations,tracks' },
  { name: 'Flowers & Blooms',       topics: 'flowers,blooms,spring' },
  { name: 'Puzzles',                topics: 'puzzles,jigsaws,riddles' },
  { name: 'Camping',                topics: 'camping,tents,wilderness' },
  { name: 'Sharks & Rays',          topics: 'sharks,rays,cartilage' },
  { name: 'Colours',                topics: 'colours,spectrum,rainbow' },
  { name: 'Clocks',                 topics: 'clocks,watches,time' },
  { name: 'Bees',                   topics: 'bees,hives,nectar' },
  { name: 'Libraries',              topics: 'libraries,shelves,books' },
  { name: 'Spices',                 topics: 'spices,pepper,cinnamon' },
  { name: 'Archaeology & Ruins',    topics: 'ruins,archaeology,ancient' },
  { name: 'Surfing & Waves',        topics: 'surfing,waves,ocean' },
  // May (31)
  { name: 'Blossom & Spring',       topics: 'blossom,spring,flowers' },
  { name: 'Honey & Bees',           topics: 'honey,bees,hive' },
  { name: 'Frogs & Tadpoles',       topics: 'tadpoles,frogs,pond' },
  { name: 'Cycling & Bikes',        topics: 'cycling,bikes,pedals' },
  { name: 'Pottery',                topics: 'pottery,clay,kiln' },
  { name: 'Storms',                 topics: 'storms,thunder,lightning' },
  { name: 'Cats & Kittens',         topics: 'cats,kittens,felines' },
  { name: 'Dogs & Puppies',         topics: 'dogs,puppies,canines' },
  { name: 'Grains & Cereals',       topics: 'grains,cereals,wheat' },
  { name: 'Martial Arts',           topics: 'karate,judo,combat' },
  { name: 'Coral & Reefs',          topics: 'coral,reefs,polyps' },
  { name: 'Mountain Hiking',        topics: 'mountains,hiking,altitude' },
  { name: 'Submarines & Diving',    topics: 'submarines,diving,depth' },
  { name: 'Herbs & Spices',         topics: 'herbs,spices,seasoning' },
  { name: 'Archaeology & Digs',     topics: 'digs,archaeology,fossils' },
  { name: 'Surfing & Beaches',      topics: 'surfing,beaches,waves' },
  { name: 'Mushrooms',              topics: 'mushrooms,fungi,forest' },
  { name: 'Knitting',               topics: 'knitting,yarn,needles' },
  { name: 'Eggs',                   topics: 'eggs,shells,yolk' },
  { name: 'Kites',                  topics: 'kites,wind,string' },
  { name: 'Rain & Storms',          topics: 'rain,storms,thunder' },
  { name: 'Ponds & Lakes',          topics: 'ponds,lakes,freshwater' },
  { name: 'Chocolate & Cocoa',      topics: 'chocolate,cocoa,cacao' },
  { name: 'Planets & Moons',        topics: 'planets,moons,solar system' },
  { name: 'Painting',               topics: 'painting,brushes,canvas' },
  { name: 'Snakes & Lizards',       topics: 'snakes,lizards,reptiles' },
  { name: 'Origami & Paper',        topics: 'origami,paper,folding' },
  { name: 'Whales & Dolphins',      topics: 'whales,dolphins,cetaceans' },
  { name: 'Bread & Yeast',          topics: 'bread,yeast,dough' },
  { name: 'Castles & Knights',      topics: 'castles,knights,medieval' },
  { name: 'Butterflies & Flowers',  topics: 'butterflies,flowers,nectar' },
  // June (30)
  { name: 'Summer & Sun',           topics: 'summer,sun,heat' },
  { name: 'Swimming & Pools',       topics: 'swimming,pools,water' },
  { name: 'Ice Cream & Gelato',     topics: 'ice cream,gelato,frozen' },
  { name: 'Festivals & Fairs',      topics: 'festivals,fairs,celebrations' },
  { name: 'Camping & Fires',        topics: 'camping,campfire,outdoors' },
  { name: 'Sailing & Yachts',       topics: 'sailing,yachts,marina' },
  { name: 'Sunflowers',             topics: 'sunflowers,seeds,yellow' },
  { name: 'Barbecue & Grilling',    topics: 'barbecue,grilling,smoke' },
  { name: 'Beaches & Sand',         topics: 'beaches,sand,shore' },
  { name: 'Fireflies & Night',      topics: 'fireflies,night,glow' },
  { name: 'Strawberries & Berries', topics: 'strawberries,berries,fruit' },
  { name: 'Hiking & Trails',        topics: 'hiking,trails,backpacking' },
  { name: 'Astronomy & Solstice',   topics: 'solstice,astronomy,sun' },
  { name: 'Frisbee & Outdoor Games',topics: 'frisbee,outdoor,games' },
  { name: 'Tropical Fish',          topics: 'tropical,fish,aquarium' },
  { name: 'Lemonade & Drinks',      topics: 'lemonade,drinks,refreshing' },
  { name: 'Butterflies & Gardens',  topics: 'butterflies,gardens,flowers' },
  { name: 'Volleyball & Beach',     topics: 'volleyball,beach,sports' },
  { name: 'Picnics & Parks',        topics: 'picnics,parks,outdoors' },
  { name: 'Rainbows',               topics: 'rainbows,colours,light' },
  { name: 'Crabs & Lobsters',       topics: 'crabs,lobsters,crustaceans' },
  { name: 'Sunsets & Horizons',     topics: 'sunsets,horizons,sky' },
  { name: 'Watermelons & Fruit',    topics: 'watermelons,fruit,summer' },
  { name: 'Sandcastles',            topics: 'sandcastles,sand,beach' },
  { name: 'Hammocks & Relaxing',    topics: 'hammocks,relaxing,leisure' },
  { name: 'Seashells',              topics: 'seashells,shells,beach' },
  { name: 'Lighthouses',            topics: 'lighthouses,coast,navigation' },
  { name: 'Turtles & Tortoises',    topics: 'turtles,tortoises,reptiles' },
  { name: 'Mangoes & Tropics',      topics: 'mangoes,tropical,fruit' },
  { name: 'Kayaking & Canoeing',    topics: 'kayaking,canoeing,paddling' },
  // July (31)
  { name: 'Fireworks & Celebrations', topics: 'fireworks,celebrations,festivals' },
  { name: 'Hot Air Balloons',       topics: 'balloons,flight,sky' },
  { name: 'Deserts & Dunes',        topics: 'deserts,dunes,sand' },
  { name: 'Parrots & Tropical Birds', topics: 'parrots,tropical,birds' },
  { name: 'Surfboards & Waves',     topics: 'surfboards,waves,surfing' },
  { name: 'Coconuts & Palms',       topics: 'coconuts,palms,tropical' },
  { name: 'Snorkelling & Diving',   topics: 'snorkelling,diving,reef' },
  { name: 'Waterparks & Slides',    topics: 'waterparks,slides,water' },
  { name: 'Ants & Colonies',        topics: 'ants,colonies,insects' },
  { name: 'Sunscreen & Skin',       topics: 'sunscreen,skin,protection' },
  { name: 'Pineapples & Tropics',   topics: 'pineapples,tropical,fruit' },
  { name: 'Skateboarding',          topics: 'skateboarding,tricks,ramps' },
  { name: 'Astronomy & Comets',     topics: 'comets,asteroids,space' },
  { name: 'Sandals & Footwear',     topics: 'sandals,footwear,summer' },
  { name: 'Jellyfish',              topics: 'jellyfish,tentacles,ocean' },
  { name: 'Hammers & Tools',        topics: 'hammers,tools,carpentry' },
  { name: 'Lava Lamps & Retro',     topics: 'retro,vintage,nostalgia' },
  { name: 'Frogs & Lily Pads',      topics: 'frogs,lily pads,pond' },
  { name: 'Treasure & Pirates',     topics: 'treasure,pirates,gold' },
  { name: 'Mangoes & Papayas',      topics: 'mangoes,papayas,tropical' },
  { name: 'Cycling & Tours',        topics: 'cycling,tours,racing' },
  { name: 'Archery',                topics: 'archery,arrows,bows' },
  { name: 'Dolphins & Porpoises',   topics: 'dolphins,porpoises,marine' },
  { name: 'Hammocks & Shade',       topics: 'hammocks,shade,relaxing' },
  { name: 'Crabs & Tides',          topics: 'crabs,tides,shore' },
  { name: 'Sunflowers & Fields',    topics: 'sunflowers,fields,yellow' },
  { name: 'Kayaking & Rivers',      topics: 'kayaking,rivers,rapids' },
  { name: 'Seagulls & Coasts',      topics: 'seagulls,coasts,birds' },
  { name: 'Watermelons',            topics: 'watermelons,seeds,summer' },
  { name: 'Sandcastles & Moats',    topics: 'sandcastles,moats,beach' },
  { name: 'Lighthouses & Fog',      topics: 'lighthouses,fog,coast' },
  // August (31)
  { name: 'Back to School',         topics: 'school,education,learning' },
  { name: 'Harvest & Crops',        topics: 'harvest,crops,farming' },
  { name: 'Sunsets & Dusk',         topics: 'sunsets,dusk,twilight' },
  { name: 'Camping & Stars',        topics: 'camping,stars,night' },
  { name: 'Corn & Maize',           topics: 'corn,maize,harvest' },
  { name: 'Dragonflies',            topics: 'dragonflies,insects,ponds' },
  { name: 'Peaches & Plums',        topics: 'peaches,plums,stone fruit' },
  { name: 'Rowing & Regattas',      topics: 'rowing,regattas,boats' },
  { name: 'Astronomy & Meteors',    topics: 'meteors,shooting stars,sky' },
  { name: 'Grasshoppers & Crickets',topics: 'grasshoppers,crickets,insects' },
  { name: 'Sunflower Seeds',        topics: 'seeds,sunflowers,harvest' },
  { name: 'Skateparks',             topics: 'skateparks,ramps,tricks' },
  { name: 'Tomatoes & Vegetables',  topics: 'tomatoes,vegetables,garden' },
  { name: 'Sailing & Regattas',     topics: 'sailing,regattas,racing' },
  { name: 'Bats & Nocturnal',       topics: 'bats,nocturnal,night' },
  { name: 'Lavender & Herbs',       topics: 'lavender,herbs,fragrance' },
  { name: 'Cycling & Mountains',    topics: 'cycling,mountains,altitude' },
  { name: 'Crabs & Rockpools',      topics: 'crabs,rockpools,shore' },
  { name: 'Figs & Dates',           topics: 'figs,dates,fruit' },
  { name: 'Archery & Targets',      topics: 'archery,targets,precision' },
  { name: 'Dolphins & Surfing',     topics: 'dolphins,surfing,ocean' },
  { name: 'Hammers & Nails',        topics: 'hammers,nails,carpentry' },
  { name: 'Treasure Maps',          topics: 'treasure maps,pirates,adventure' },
  { name: 'Mangoes & Smoothies',    topics: 'mangoes,smoothies,blending' },
  { name: 'Frogs & Croaking',       topics: 'frogs,croaking,night' },
  { name: 'Seashells & Collecting', topics: 'seashells,collecting,beach' },
  { name: 'Jellyfish & Plankton',   topics: 'jellyfish,plankton,ocean' },
  { name: 'Sandcastles & Waves',    topics: 'sandcastles,waves,beach' },
  { name: 'Lighthouses & Ships',    topics: 'lighthouses,ships,navigation' },
  { name: 'Turtles & Nesting',      topics: 'turtles,nesting,beach' },
  { name: 'Kayaking & Waterfalls',  topics: 'kayaking,waterfalls,rivers' },
  // September (30)
  { name: 'Autumn & Leaves',        topics: 'autumn,leaves,fall' },
  { name: 'Apples & Orchards',      topics: 'apples,orchards,harvest' },
  { name: 'Spiders & Webs',         topics: 'spiders,webs,arachnids' },
  { name: 'Pumpkins & Gourds',      topics: 'pumpkins,gourds,harvest' },
  { name: 'Acorns & Squirrels',     topics: 'acorns,squirrels,nuts' },
  { name: 'Mushrooms & Foraging',   topics: 'mushrooms,foraging,forest' },
  { name: 'Harvest Moon',           topics: 'harvest moon,autumn,sky' },
  { name: 'Cider & Apples',         topics: 'cider,apples,fermentation' },
  { name: 'Hedgehogs',              topics: 'hedgehogs,spines,nocturnal' },
  { name: 'Conkers & Chestnuts',    topics: 'conkers,chestnuts,autumn' },
  { name: 'Fog & Mist',             topics: 'fog,mist,atmosphere' },
  { name: 'Owls & Night',           topics: 'owls,night,hunting' },
  { name: 'Grapes & Vineyards',     topics: 'grapes,vineyards,harvest' },
  { name: 'Scarecrows & Fields',    topics: 'scarecrows,fields,farming' },
  { name: 'Deer & Stags',           topics: 'deer,stags,antlers' },
  { name: 'Pears & Quinces',        topics: 'pears,quinces,fruit' },
  { name: 'Cobwebs & Spiders',      topics: 'cobwebs,spiders,silk' },
  { name: 'Walnuts & Hazelnuts',    topics: 'walnuts,hazelnuts,nuts' },
  { name: 'Geese & Migration',      topics: 'geese,migration,birds' },
  { name: 'Bonfires & Smoke',       topics: 'bonfires,smoke,fire' },
  { name: 'Foxes & Dens',           topics: 'foxes,dens,cunning' },
  { name: 'Pumpkin Carving',        topics: 'pumpkins,carving,halloween' },
  { name: 'Wool & Knitting',        topics: 'wool,knitting,yarn' },
  { name: 'Crows & Ravens',         topics: 'crows,ravens,black birds' },
  { name: 'Harvest Festivals',      topics: 'harvest,festivals,celebration' },
  { name: 'Badgers & Burrows',      topics: 'wildlife,burrows,mammals' },
  { name: 'Maple Syrup',            topics: 'maple,syrup,trees' },
  { name: 'Scarves & Coats',        topics: 'scarves,coats,autumn' },
  { name: 'Berries & Brambles',     topics: 'berries,brambles,foraging' },
  { name: 'Toadstools & Fungi',     topics: 'toadstools,fungi,forest' },
  // October (31)
  { name: 'Halloween & Ghosts',     topics: 'halloween,ghosts,spooky' },
  { name: 'Witches & Cauldrons',    topics: 'witches,cauldrons,magic' },
  { name: 'Pumpkins & Lanterns',    topics: 'pumpkins,lanterns,carving' },
  { name: 'Bats & Caves',           topics: 'bats,caves,nocturnal' },
  { name: 'Skeletons & Bones',      topics: 'skeletons,bones,anatomy' },
  { name: 'Spiders & Webs',         topics: 'spiders,webs,silk' },
  { name: 'Vampires & Castles',     topics: 'vampires,castles,gothic' },
  { name: 'Zombies & Horror',       topics: 'zombies,horror,undead' },
  { name: 'Candy & Trick or Treat', topics: 'candy,trick or treat,sweets' },
  { name: 'Autumn Colours',         topics: 'autumn,colours,leaves' },
  { name: 'Owls & Moonlight',       topics: 'owls,moonlight,night' },
  { name: 'Fog & Graveyards',       topics: 'fog,graveyards,eerie' },
  { name: 'Wolves & Howling',       topics: 'wolves,howling,moon' },
  { name: 'Potions & Magic',        topics: 'potions,magic,spells' },
  { name: 'Scarecrows',             topics: 'scarecrows,fields,straw' },
  { name: 'Crows & Omens',          topics: 'crows,omens,ravens' },
  { name: 'Haunted Houses',         topics: 'haunted,houses,ghosts' },
  { name: 'Mummies & Egypt',        topics: 'mummies,egypt,tombs' },
  { name: 'Black Cats',             topics: 'black cats,superstition,luck' },
  { name: 'Frankenstein & Monsters',topics: 'frankenstein,monsters,horror' },
  { name: 'Mazes & Labyrinths',     topics: 'mazes,labyrinths,puzzles' },
  { name: 'Fog & Mystery',          topics: 'fog,mystery,unknown' },
  { name: 'Cauldrons & Brews',      topics: 'cauldrons,brews,potions' },
  { name: 'Gargoyles & Gothic',     topics: 'gargoyles,gothic,architecture' },
  { name: 'Werewolves',             topics: 'werewolves,transformation,moon' },
  { name: 'Cobwebs & Dust',         topics: 'cobwebs,dust,abandoned' },
  { name: 'Lanterns & Candles',     topics: 'lanterns,candles,light' },
  { name: 'Autumn Harvest',         topics: 'harvest,autumn,abundance' },
  { name: 'Pumpkin Spice',          topics: 'pumpkin,spice,autumn' },
  { name: 'Costumes & Masks',       topics: 'costumes,masks,disguise' },
  { name: 'Candy Corn & Sweets',    topics: 'candy corn,sweets,halloween' },
  // November (30)
  { name: 'Bonfire Night',          topics: 'bonfires,fireworks,gunpowder' },
  { name: 'Remembrance & Poppies',  topics: 'poppies,remembrance,war' },
  { name: 'Fog & Frost',            topics: 'fog,frost,cold' },
  { name: 'Squirrels & Nuts',       topics: 'squirrels,nuts,hoarding' },
  { name: 'Thanksgiving & Feasts',  topics: 'thanksgiving,feasts,gratitude' },
  { name: 'Turkeys & Stuffing',     topics: 'turkeys,stuffing,roasting' },
  { name: 'Pies & Pastries',        topics: 'pies,pastries,baking' },
  { name: 'Scarves & Mittens',      topics: 'scarves,mittens,warmth' },
  { name: 'Deer & Antlers',         topics: 'deer,antlers,forest' },
  { name: 'Chestnuts & Fires',      topics: 'chestnuts,fires,roasting' },
  { name: 'Geese & Flocks',         topics: 'geese,flocks,migration' },
  { name: 'Hedgehogs & Hibernation',topics: 'hedgehogs,hibernation,winter' },
  { name: 'Soup & Stews',           topics: 'soup,stews,warming' },
  { name: 'Candles & Warmth',       topics: 'candles,warmth,light' },
  { name: 'Foxes & Forests',        topics: 'foxes,forests,cunning' },
  { name: 'Wool & Fleece',          topics: 'wool,fleece,warmth' },
  { name: 'Badgers & Setts',        topics: 'badgers,woodland,mammals' },
  { name: 'Mushrooms & Damp',       topics: 'mushrooms,damp,forest' },
  { name: 'Owls & Hunting',         topics: 'owls,hunting,silent' },
  { name: 'Berries & Hedgerows',    topics: 'berries,hedgerows,foraging' },
  { name: 'Crows & Ravens',         topics: 'crows,ravens,birds' },
  { name: 'Mud & Puddles',          topics: 'mud,puddles,rain' },
  { name: 'Fireside & Logs',        topics: 'fireside,logs,warmth' },
  { name: 'Weasels & Stoats',       topics: 'weasels,ferrets,mammals' },
  { name: 'Pumpkin Soup',           topics: 'pumpkin,soup,autumn' },
  { name: 'Starlings & Flocking',   topics: 'starlings,flocking,birds' },
  { name: 'Frost & Ice',            topics: 'frost,ice,freezing' },
  { name: 'Robins & Redbreasts',    topics: 'robins,redbreasts,winter' },
  { name: 'Pinecones & Firs',       topics: 'pinecones,firs,conifers' },
  { name: 'Mist & Valleys',         topics: 'mist,valleys,morning' },
  // December (31)
  { name: 'Christmas & Gifts',      topics: 'christmas,gifts,presents' },
  { name: 'Snow & Snowflakes',      topics: 'snow,snowflakes,winter' },
  { name: 'Reindeer & Sleighs',     topics: 'reindeer,sleighs,christmas' },
  { name: 'Elves & Workshops',      topics: 'elves,workshops,toys' },
  { name: 'Christmas Trees',        topics: 'christmas trees,decorations,ornaments' },
  { name: 'Candles & Advent',       topics: 'candles,advent,christmas' },
  { name: 'Gingerbread & Cookies',  topics: 'gingerbread,cookies,baking' },
  { name: 'Carols & Singing',       topics: 'carols,singing,christmas' },
  { name: 'Stockings & Fireplaces', topics: 'stockings,fireplaces,christmas' },
  { name: 'Snowmen & Scarves',      topics: 'snowmen,scarves,winter' },
  { name: 'Holly & Mistletoe',      topics: 'holly,mistletoe,christmas' },
  { name: 'Bells & Jingles',        topics: 'bells,jingles,christmas' },
  { name: 'Wrapping & Ribbons',     topics: 'wrapping,ribbons,gifts' },
  { name: 'Mulled Wine & Spices',   topics: 'mulled wine,spices,warmth' },
  { name: 'Polar Bears & Arctic',   topics: 'polar bears,arctic,ice' },
  { name: 'Penguins & Antarctica',  topics: 'penguins,antarctica,cold' },
  { name: 'Ice Skating',            topics: 'ice skating,rinks,winter' },
  { name: 'Snowboarding & Skiing',  topics: 'snowboarding,skiing,slopes' },
  { name: 'Yule & Traditions',      topics: 'yule,traditions,winter' },
  { name: 'Nutcrackers & Ballet',   topics: 'nutcrackers,ballet,christmas' },
  { name: 'Tinsel & Baubles',       topics: 'tinsel,baubles,decorations' },
  { name: 'Chestnuts & Roasting',   topics: 'chestnuts,roasting,fire' },
  { name: 'Eggnog & Drinks',        topics: 'eggnog,drinks,christmas' },
  { name: 'Wreath & Garlands',      topics: 'wreaths,garlands,christmas' },
  { name: 'Icicles & Frost',        topics: 'icicles,frost,winter' },
  { name: 'Boxing Day & Leftovers', topics: 'boxing day,leftovers,feasting' },
  { name: 'New Year & Fireworks',   topics: 'new year,fireworks,celebrations' },
  { name: 'Resolutions & Goals',    topics: 'resolutions,goals,new year' },
  { name: 'Champagne & Toasts',     topics: 'champagne,toasts,celebrations' },
  { name: 'Midnight & Clocks',      topics: 'midnight,clocks,new year' },
  { name: 'Winter Solstice',        topics: 'winter solstice,darkness,light' },
];
