// 665 themes for Span.IT — cycles through all available themes
// Each theme has a display name (cryptic hint) and Datamuse API topics string
export const THEMES = [
  // January (31)
  { name: 'The Deep Blue',     topics: 'ocean' },
  { name: 'The Final Frontier', topics: 'space' },
  { name: 'Heat of the Kitchen', topics: 'cooking' },
  { name: 'Lost Civilizations', topics: 'history' },
  { name: 'Sound & Soul',      topics: 'music' },
  { name: 'Under the Sky',     topics: 'weather' },
  { name: 'The Playing Field', topics: 'sports' },
  { name: 'Ones and Zeros',    topics: 'technology' },
  { name: 'The Wild Kingdom',  topics: 'animals' },
  { name: 'Built to Last',     topics: 'architecture' },
  { name: 'Under the Skin',    topics: 'anatomy' },
  { name: 'Wanderlust',        topics: 'travel' },
  { name: 'Brush Strokes',     topics: 'art' },
  { name: 'Lab Coats',         topics: 'science' },
  { name: 'Gods & Legends',    topics: 'mythology' },
  { name: 'On the Runway',     topics: 'fashion' },
  { name: 'Green Thumbs',      topics: 'gardening' },
  { name: 'Silver Screen',     topics: 'cinema' },
  { name: 'By the Numbers',    topics: 'mathematics' },
  { name: 'Words & Grammar',   topics: 'language' },
  { name: 'Into the Woods',    topics: 'forest' },
  { name: 'Six Legs',          topics: 'insects' },
  { name: 'Heart & Mind',      topics: 'emotions' },
  { name: 'Around the Globe',  topics: 'geography' },
  { name: 'Before Our Time',   topics: 'dinosaurs' },
  { name: 'Plough & Harvest',  topics: 'farming' },
  { name: 'The Healing Arts',  topics: 'medicine' },
  { name: 'Capes & Powers',    topics: 'superheroes' },
  { name: 'Gazing Upward',     topics: 'astronomy' },
  { name: 'Old Wives Tales',   topics: 'folklore' },
  { name: 'The Cold Months',   topics: 'winter' },
  // February (28)
  { name: 'Matters of the Heart', topics: 'romance' },
  { name: 'Sweet Indulgence',  topics: 'chocolate' },
  { name: 'Feathered Friends', topics: 'birds' },
  { name: 'Beneath the Waves', topics: 'oceans' },
  { name: 'Layers of Earth',   topics: 'geology' },
  { name: 'Say Cheese',        topics: 'photography' },
  { name: 'Rhythm & Movement', topics: 'dance' },
  { name: 'Cold Blooded',      topics: 'reptiles' },
  { name: 'In the Oven',       topics: 'baking' },
  { name: 'Moats & Towers',    topics: 'castles' },
  { name: 'Floating Above',    topics: 'clouds' },
  { name: 'Made of Metal',     topics: 'robots' },
  { name: 'Hidden Sparkle',    topics: 'gems' },
  { name: "All the World's a Stage", topics: 'theatre' },
  { name: 'Endless Sand',      topics: 'desert' },
  { name: 'Rod & Reel',        topics: 'fishing' },
  { name: 'Mane & Hoof',       topics: 'horses' },
  { name: 'Spanning the Gap',  topics: 'bridges' },
  { name: 'Aged to Perfection', topics: 'cheese' },
  { name: 'Dark Below',        topics: 'caves' },
  { name: 'Breathe & Stretch', topics: 'yoga' },
  { name: 'All Aboard',        topics: 'trains' },
  { name: 'Petals & Stems',    topics: 'flowers' },
  { name: 'Missing Pieces',    topics: 'puzzles' },
  { name: 'Under the Stars',   topics: 'camping' },
  { name: 'Jaws',              topics: 'sharks' },
  { name: 'Shades & Hues',     topics: 'colour' },
  { name: 'Tick Tock',         topics: 'clocks' },
  // March (31)
  { name: 'New Beginnings',    topics: 'spring' },
  { name: 'Lily Pad Life',     topics: 'frogs' },
  { name: 'Wind in the Sails', topics: 'sailing' },
  { name: 'Bubbling Over',     topics: 'fermentation' },
  { name: 'The Green Canopy',  topics: 'rainforest' },
  { name: 'Two Wheels',        topics: 'cycling' },
  { name: 'Wheel & Kiln',      topics: 'pottery' },
  { name: 'Rumbles Above',     topics: 'storms' },
  { name: 'Nine Lives',        topics: 'cats' },
  { name: 'Best Friend',       topics: 'dogs' },
  { name: 'Rise & Bake',       topics: 'bread' },
  { name: 'Fire Mountain',     topics: 'volcanoes' },
  { name: 'The Dojo',          topics: 'combat' },
  { name: 'Painted Wings',     topics: 'butterflies' },
  { name: 'From the Vine',     topics: 'wine' },
  { name: 'Cogs & Wheels',     topics: 'machines' },
  { name: 'Underwater Cities', topics: 'coral' },
  { name: 'The Long Walk',     topics: 'hiking' },
  { name: 'Buzz & Sting',      topics: 'bees' },
  { name: 'Quiet Shelves',     topics: 'libraries' },
  { name: 'Below the Surface', topics: 'submarines' },
  { name: 'Flavour & Heat',    topics: 'spices' },
  { name: 'Digging Up the Past', topics: 'archaeology' },
  { name: 'Catching Waves',    topics: 'surfing' },
  { name: 'Forest Floor',      topics: 'mushrooms' },
  { name: 'Twinkling Above',   topics: 'stars' },
  { name: 'Stitch by Stitch',  topics: 'knitting' },
  { name: 'Warty Hoppers',     topics: 'toads' },
  { name: 'From the Cow',      topics: 'dairy' },
  { name: 'Soaring High',      topics: 'kites' },
  { name: 'Before They Hatch', topics: 'eggs' },
  // April (30)
  { name: 'Drip Drop',         topics: 'rain' },
  { name: 'Still Waters',      topics: 'ponds' },
  { name: 'Tiny Beginnings',   topics: 'seeds' },
  { name: 'Tropical Bean',     topics: 'cocoa' },
  { name: 'Orbiting the Sun',  topics: 'planets' },
  { name: 'Canvas & Colour',   topics: 'painting' },
  { name: 'No Legs',           topics: 'snakes' },
  { name: 'Across the River',  topics: 'spans' },
  { name: 'Snap & Crunch',     topics: 'crackers' },
  { name: 'Puffy & White',     topics: 'cumulus' },
  { name: 'Paper Folding',     topics: 'origami' },
  { name: 'Gentle Giants',     topics: 'whales' },
  { name: 'Fresh from the Oven', topics: 'loaves' },
  { name: 'High Above',        topics: 'towers' },
  { name: 'Taking Flight',     topics: 'wings' },
  { name: 'Afloat',            topics: 'boats' },
  { name: 'Molten Rock',       topics: 'lava' },
  { name: 'Hold the Position', topics: 'poses' },
  { name: 'Down the Line',     topics: 'tracks' },
  { name: 'In Full Flower',    topics: 'blooms' },
  { name: 'Piece by Piece',    topics: 'jigsaws' },
  { name: 'Canvas & Pegs',     topics: 'tents' },
  { name: 'Flat & Finned',     topics: 'rays' },
  { name: 'Every Colour',      topics: 'spectrum' },
  { name: 'On Your Wrist',     topics: 'watches' },
  { name: 'Wax & Honey',       topics: 'hives' },
  { name: 'Rows of Books',     topics: 'shelves' },
  { name: 'Grind & Season',    topics: 'pepper' },
  { name: 'What Remains',      topics: 'ruins' },
  { name: 'Crash & Curl',      topics: 'waves' },
  // May (31)
  { name: 'Pink & White',      topics: 'blossom' },
  { name: 'Liquid Gold',       topics: 'honey' },
  { name: 'Growing Legs',      topics: 'tadpoles' },
  { name: 'Pedal Power',       topics: 'bikes' },
  { name: 'Shaped by Hands',   topics: 'clay' },
  { name: 'Flash & Rumble',    topics: 'thunder' },
  { name: 'Tiny Paws',         topics: 'kittens' },
  { name: 'Wet Noses',         topics: 'puppies' },
  { name: 'Golden Fields',     topics: 'grains' },
  { name: 'The Way of the Hand', topics: 'karate' },
  { name: 'Living Colour Below', topics: 'reefs' },
  { name: 'Summit Seekers',    topics: 'mountains' },
  { name: 'Going Under',       topics: 'diving' },
  { name: 'Fresh & Fragrant',  topics: 'herbs' },
  { name: 'Turned to Stone',   topics: 'fossils' },
  { name: 'Sand Between Toes', topics: 'beaches' },
  { name: 'Spores & Caps',     topics: 'fungi' },
  { name: 'Ball & Needle',     topics: 'yarn' },
  { name: 'Washed Ashore',     topics: 'shells' },
  { name: 'Tied & Taut',       topics: 'string' },
  { name: 'After the Rain',    topics: 'puddles' },
  { name: 'Calm Waters',       topics: 'lakes' },
  { name: "Chocolate's Origin", topics: 'cacao' },
  { name: 'Orbiting Worlds',   topics: 'moons' },
  { name: 'Dip & Stroke',      topics: 'brushes' },
  { name: 'Scales & Sun',      topics: 'lizards' },
  { name: 'Fold & Cut',        topics: 'paper' },
  { name: 'Smiling Swimmers',  topics: 'dolphins' },
  { name: 'Knead & Prove',     topics: 'dough' },
  { name: 'Chivalry & Armour', topics: 'knights' },
  { name: 'Sweet Sip',         topics: 'nectar' },
  // June (30)
  { name: 'Longest Days',      topics: 'summer' },
  { name: 'Making Laps',       topics: 'swimming' },
  { name: 'Scooped & Cold',    topics: 'gelato' },
  { name: 'Music & Crowds',    topics: 'festivals' },
  { name: 'Crackling Flames',  topics: 'campfire' },
  { name: 'Sails & Luxury',    topics: 'yachts' },
  { name: 'Facing the Sun',    topics: 'sunflowers' },
  { name: 'Smoke & Grill',     topics: 'barbecue' },
  { name: 'Grains Underfoot',  topics: 'sand' },
  { name: 'Blinking Lights',   topics: 'fireflies' },
  { name: 'Red & Sweet',       topics: 'strawberries' },
  { name: 'Winding Paths',     topics: 'trails' },
  { name: 'Longest Day',       topics: 'solstice' },
  { name: 'Toss & Catch',      topics: 'frisbee' },
  { name: 'Palm Trees & Heat', topics: 'tropical' },
  { name: 'When Life Gives You Lemons', topics: 'lemonade' },
  { name: 'Blooming Rows',     topics: 'gardens' },
  { name: 'Net & Sand',        topics: 'volleyball' },
  { name: 'Blanket on the Grass', topics: 'picnics' },
  { name: 'After the Storm',   topics: 'rainbows' },
  { name: 'Sideways Walkers',  topics: 'crabs' },
  { name: 'Golden Hour',       topics: 'sunsets' },
  { name: 'Green & Juicy',     topics: 'watermelons' },
  { name: 'Built to Fall',     topics: 'sandcastles' },
  { name: 'Swaying Gently',    topics: 'hammocks' },
  { name: 'Treasures of the Shore', topics: 'seashells' },
  { name: 'Guiding Light',     topics: 'lighthouses' },
  { name: 'Slow & Steady',     topics: 'turtles' },
  { name: 'Tropical & Juicy',  topics: 'mangoes' },
  { name: 'Paddle & Glide',    topics: 'kayaking' },
  // July (31)
  { name: 'Night Sky Explosions', topics: 'fireworks' },
  { name: 'Up & Away',         topics: 'balloons' },
  { name: 'Shifting Sands',    topics: 'dunes' },
  { name: 'Colourful Talkers', topics: 'parrots' },
  { name: 'Waxed & Ready',     topics: 'surfboards' },
  { name: 'Hard Shell Inside', topics: 'coconuts' },
  { name: 'Mask & Fins',       topics: 'snorkelling' },
  { name: 'Slides & Splashes', topics: 'waterparks' },
  { name: 'Tiny but Mighty',   topics: 'ants' },
  { name: 'Slip Slop Slap',    topics: 'sunscreen' },
  { name: 'Spiky Crown',       topics: 'pineapples' },
  { name: 'Kickflips',         topics: 'skateboarding' },
  { name: 'Icy Travellers',    topics: 'comets' },
  { name: 'Open Toes',         topics: 'sandals' },
  { name: 'Drifting Stingers', topics: 'jellyfish' },
  { name: 'Nail & Swing',      topics: 'hammers' },
  { name: 'Throwback',         topics: 'retro' },
  { name: 'Floating Green',    topics: 'lilypads' },
  { name: 'X Marks the Spot',  topics: 'treasure' },
  { name: 'Tropical & Orange', topics: 'papayas' },
  { name: 'The Open Road',     topics: 'tours' },
  { name: 'Bow & Arrow',       topics: 'archery' },
  { name: 'Smaller Cousins',   topics: 'porpoises' },
  { name: 'Cool & Dark',       topics: 'shade' },
  { name: 'In & Out',          topics: 'tides' },
  { name: 'Wide Open',         topics: 'fields' },
  { name: 'Flowing Downhill',  topics: 'rivers' },
  { name: 'Chip Stealers',     topics: 'seagulls' },
  { name: 'Thick & Sweet',     topics: 'melons' },
  { name: 'Water Barrier',     topics: 'moats' },
  { name: "Can't See Far",    topics: 'fog' },
  // August (31)
  { name: 'Back to the Books', topics: 'school' },
  { name: 'Gathering Time',    topics: 'harvest' },
  { name: 'Between Day & Night', topics: 'twilight' },
  { name: 'Looking Up',        topics: 'stargazing' },
  { name: 'Rows of Gold',      topics: 'corn' },
  { name: 'Hovering Wings',    topics: 'dragonflies' },
  { name: 'Fuzzy & Sweet',     topics: 'peaches' },
  { name: 'Pull Together',     topics: 'rowing' },
  { name: 'Shooting Stars',    topics: 'meteors' },
  { name: 'Chirping Jumpers',  topics: 'grasshoppers' },
  { name: 'Seeds Inside',      topics: 'sunflower' },
  { name: 'Ramps & Rails',     topics: 'skateparks' },
  { name: 'Red & Round',       topics: 'tomatoes' },
  { name: 'Racing on Water',   topics: 'regattas' },
  { name: 'Upside Down Sleepers', topics: 'bats' },
  { name: 'Purple Fields',     topics: 'lavender' },
  { name: 'Thin Air',          topics: 'altitude' },
  { name: 'Tideline Treasures', topics: 'rockpools' },
  { name: 'Sweet & Sticky',    topics: 'figs' },
  { name: 'Bullseye',          topics: 'targets' },
  { name: 'Under the Sea',     topics: 'marine' },
  { name: 'Hammer Time',       topics: 'nails' },
  { name: 'Ahoy Matey',        topics: 'pirates' },
  { name: 'Blended Up',        topics: 'smoothies' },
  { name: 'Night Chorus',      topics: 'croaking' },
  { name: 'Gathered Treasures', topics: 'collecting' },
  { name: 'Microscopic Drifters', topics: 'plankton' },
  { name: 'Where Land Meets Sea', topics: 'shore' },
  { name: 'Finding the Way',   topics: 'navigation' },
  { name: 'Eggs in the Branches', topics: 'nesting' },
  { name: 'Falling Water',     topics: 'waterfalls' },
  // September (30)
  { name: 'Falling Leaves',    topics: 'autumn' },
  { name: 'Orchard Picking',   topics: 'apples' },
  { name: 'Eight Legs',        topics: 'spiders' },
  { name: 'Orange & Round',    topics: 'pumpkins' },
  { name: 'Squirrel Snacks',   topics: 'acorns' },
  { name: "Nature's Pantry",  topics: 'foraging' },
  { name: 'Silver Glow',       topics: 'moonlight' },
  { name: 'Pressed & Fizzy',   topics: 'cider' },
  { name: 'Spiny & Small',     topics: 'hedgehogs' },
  { name: 'Roasted & Sweet',   topics: 'chestnuts' },
  { name: 'Veiled Morning',    topics: 'mist' },
  { name: 'Night Hunters',     topics: 'owls' },
  { name: 'On the Vine',       topics: 'grapes' },
  { name: 'Standing Guard',    topics: 'scarecrows' },
  { name: 'Antlers & Grace',   topics: 'deer' },
  { name: 'Autumn Fruit',      topics: 'pears' },
  { name: 'Silk Traps',        topics: 'cobwebs' },
  { name: 'Cracked Open',      topics: 'walnuts' },
  { name: 'V Formation',       topics: 'geese' },
  { name: 'Crackling Flames',  topics: 'bonfires' },
  { name: 'Red & Cunning',     topics: 'foxes' },
  { name: 'Chisel & Wood',     topics: 'carving' },
  { name: 'Soft & Warm',       topics: 'wool' },
  { name: 'Black & Clever',    topics: 'crows' },
  { name: 'Raise a Glass',     topics: 'celebration' },
  { name: 'Striped Face',      topics: 'badgers' },
  { name: 'Sweet Syrup',       topics: 'maple' },
  { name: 'Wrapped Up Warm',   topics: 'scarves' },
  { name: 'Thorny Sweetness',  topics: 'berries' },
  { name: 'Red & Spotted',     topics: 'toadstools' },
  // October (31)
  { name: 'Trick or Treat',    topics: 'halloween' },
  { name: 'Broomsticks',       topics: 'witches' },
  { name: 'Paper & Flame',     topics: 'lanterns' },
  { name: 'After Dark',        topics: 'nocturnal' },
  { name: 'Bones & Joints',    topics: 'skeletons' },
  { name: 'Silk & Dew',        topics: 'webs' },
  { name: 'Fangs & Capes',     topics: 'vampires' },
  { name: 'The Undead',        topics: 'zombies' },
  { name: 'Sugar Rush',        topics: 'candy' },
  { name: 'Changing Colours',  topics: 'leaves' },
  { name: 'Pale Glow',         topics: 'moonlit' },
  { name: 'Rest in Peace',     topics: 'graveyards' },
  { name: 'Howling Pack',      topics: 'wolves' },
  { name: 'Bubble Bubble',     topics: 'potions' },
  { name: 'Stuffed Man',       topics: 'straw' },
  { name: 'Dark Signs',        topics: 'omens' },
  { name: 'Creaky Doors',      topics: 'haunted' },
  { name: 'Wrapped in Cloth',  topics: 'mummies' },
  { name: 'Black Cats',        topics: 'superstition' },
  { name: 'Under the Bed',     topics: 'monsters' },
  { name: 'Dead Ends',         topics: 'mazes' },
  { name: 'Whodunnit',         topics: 'mystery' },
  { name: 'Stirring the Pot',  topics: 'cauldrons' },
  { name: 'Stone Watchers',    topics: 'gargoyles' },
  { name: 'Full Moon Rising',  topics: 'werewolves' },
  { name: 'Forgotten Rooms',   topics: 'dust' },
  { name: 'Flickering Light',  topics: 'candles' },
  { name: 'Overflowing',       topics: 'abundance' },
  { name: 'Spiced & Orange',   topics: 'pumpkin' },
  { name: 'Dress Up',          topics: 'costumes' },
  { name: 'Tooth Ache',        topics: 'sweets' },
  // November (30)
  { name: 'Remember Remember', topics: 'bonfire' },
  { name: 'Fields of Red',     topics: 'poppies' },
  { name: 'Morning Crystals',  topics: 'frost' },
  { name: 'Bushy Tails',       topics: 'squirrels' },
  { name: 'Grateful Feast',    topics: 'thanksgiving' },
  { name: 'Gobble Gobble',     topics: 'turkeys' },
  { name: 'Crust & Filling',   topics: 'pies' },
  { name: 'Warm Hands',        topics: 'mittens' },
  { name: 'Branching Crown',   topics: 'antlers' },
  { name: 'Over the Fire',     topics: 'roasting' },
  { name: 'Flying Together',   topics: 'flocks' },
  { name: 'Long Winter Sleep', topics: 'hibernation' },
  { name: 'Warm & Hearty',     topics: 'soup' },
  { name: 'Cosy Feeling',      topics: 'warmth' },
  { name: 'Sly & Quick',       topics: 'cunning' },
  { name: 'Soft Lining',       topics: 'fleece' },
  { name: 'Among the Trees',   topics: 'woodland' },
  { name: 'Moist & Dark',      topics: 'damp' },
  { name: 'On the Trail',      topics: 'hunting' },
  { name: 'Tangled Borders',   topics: 'hedgerows' },
  { name: 'Dark Feathers',     topics: 'ravens' },
  { name: 'Squelch',           topics: 'mud' },
  { name: 'By the Hearth',     topics: 'fireside' },
  { name: 'Slender & Quick',   topics: 'weasels' },
  { name: 'Simmering Pot',     topics: 'broth' },
  { name: 'Murmuration',       topics: 'starlings' },
  { name: 'Frozen Solid',      topics: 'ice' },
  { name: 'Red Breast',        topics: 'robins' },
  { name: 'Woody Seeds',       topics: 'pinecones' },
  { name: 'Low & Hidden',      topics: 'valleys' },
  // December (31)
  { name: 'The Big Day',       topics: 'christmas' },
  { name: 'No Two Alike',      topics: 'snowflakes' },
  { name: 'Red Nosed',         topics: 'reindeer' },
  { name: 'Pointy Ears',       topics: 'elves' },
  { name: 'Hanging Baubles',   topics: 'ornaments' },
  { name: 'Counting Down',     topics: 'advent' },
  { name: 'Spiced & Baked',    topics: 'gingerbread' },
  { name: 'Singing Together',  topics: 'carols' },
  { name: 'Hung by the Fire',  topics: 'stockings' },
  { name: 'Carrot Nose',       topics: 'snowmen' },
  { name: 'Prickly & Green',   topics: 'holly' },
  { name: 'Ding Dong',         topics: 'bells' },
  { name: 'Tied with a Bow',   topics: 'ribbons' },
  { name: 'Warm & Spiced',     topics: 'mulled' },
  { name: 'Polar Region',      topics: 'arctic' },
  { name: 'Tuxedo Birds',      topics: 'penguins' },
  { name: 'Blades & Glide',    topics: 'skating' },
  { name: 'Powder & Slopes',   topics: 'snowboarding' },
  { name: 'Ancient Midwinter', topics: 'yule' },
  { name: 'Wooden Soldiers',   topics: 'nutcrackers' },
  { name: 'Shiny Strands',     topics: 'tinsel' },
  { name: 'Over Hot Coals',    topics: 'roasted' },
  { name: 'Creamy & Spiced',   topics: 'eggnog' },
  { name: 'Circles on the Door', topics: 'wreaths' },
  { name: 'Dripping Cold',     topics: 'icicles' },
  { name: 'Day After',         topics: 'leftovers' },
  { name: 'Fresh Start',       topics: 'resolutions' },
  { name: 'Aiming High',       topics: 'goals' },
  { name: 'Pop & Pour',        topics: 'champagne' },
  { name: 'Stroke of Twelve',  topics: 'midnight' },
  { name: 'Shortest Day',      topics: 'solstice' },
  // Extra themes 366-465
  { name: 'Frozen Rivers',     topics: 'glaciers' },
  { name: 'Hunting Together',  topics: 'packs' },
  { name: 'Soaring Hunters',   topics: 'eagles' },
  { name: 'Hanging Down',      topics: 'stalactites' },
  { name: 'Prickly Survivors', topics: 'cacti' },
  { name: 'Pulled Along',      topics: 'currents' },
  { name: 'Blowing its Top',   topics: 'eruption' },
  { name: 'Funnel of Wind',    topics: 'tornadoes' },
  { name: 'Shaking Ground',    topics: 'earthquakes' },
  { name: 'Wall of Water',     topics: 'tsunamis' },
  { name: 'Huddle for Warmth', topics: 'colony' },
  { name: 'Pink & Leggy',      topics: 'flamingos' },
  { name: 'Never Forget',      topics: 'elephants' },
  { name: 'King of the Pride', topics: 'lions' },
  { name: 'Long Necks',        topics: 'giraffes' },
  { name: 'Black & White Stripes', topics: 'zebras' },
  { name: 'Jungle Giants',     topics: 'gorillas' },
  { name: 'Bamboo Eaters',     topics: 'pandas' },
  { name: 'Tree Huggers',      topics: 'koalas' },
  { name: 'Big Hoppers',       topics: 'kangaroos' },
  { name: 'Eight Arms',        topics: 'octopus' },
  { name: 'Tiny Horses',       topics: 'seahorses' },
  { name: 'Five Arms',         topics: 'starfish' },
  { name: 'Bottom of the World', topics: 'antarctic' },
  { name: 'The Wise Ones',     topics: 'wisdom' },
  { name: 'Diving Hunters',    topics: 'falcons' },
  { name: 'Graceful Gliders',  topics: 'swans' },
  { name: 'Fanned Display',    topics: 'peacocks' },
  { name: 'Hovering in Place', topics: 'hummingbirds' },
  { name: 'Tap Tap Tap',       topics: 'woodpeckers' },
  { name: 'Dug Through Rock',  topics: 'tunnels' },
  { name: 'Hard Shell',        topics: 'beetles' },
  { name: 'Living Light',      topics: 'glowing' },
  { name: 'Spotted & Red',     topics: 'ladybugs' },
  { name: 'Before the Wings',  topics: 'caterpillars' },
  { name: 'Curved Tail',       topics: 'scorpions' },
  { name: 'Colour Changers',   topics: 'chameleons' },
  { name: 'Ancient Jaws',      topics: 'crocodiles' },
  { name: 'River Giants',      topics: 'hippos' },
  { name: 'Horned Heavyweights', topics: 'rhinos' },
  { name: 'Fastest on Land',   topics: 'cheetahs' },
  { name: 'Spotted Stalkers',  topics: 'leopards' },
  { name: 'Striped Power',     topics: 'tigers' },
  { name: 'Cave Sleepers',     topics: 'bears' },
  { name: 'Biggest Deer',      topics: 'moose' },
  { name: 'Prairie Thunder',   topics: 'bison' },
  { name: 'Playing in Streams', topics: 'otters' },
  { name: 'Dam Builders',      topics: 'beavers' },
  { name: 'Masked Bandits',    topics: 'raccoons' },
  { name: 'Hanging Around',    topics: 'sloths' },
  { name: 'Swinging Through',  topics: 'monkeys' },
  { name: 'Copying Others',    topics: 'mimicry' },
  { name: 'Rainbow Beaks',     topics: 'toucans' },
  { name: 'Big Mouth',         topics: 'pelicans' },
  { name: 'Longest Wings',     topics: 'albatross' },
  { name: 'Cliff Dwellers',    topics: 'puffins' },
  { name: 'Baby Deliverers',   topics: 'storks' },
  { name: 'Still as Stone',    topics: 'herons' },
  { name: 'Flash of Blue',     topics: 'kingfishers' },
  { name: 'Borrowed Nests',    topics: 'cuckoos' },
  { name: 'City Dwellers',     topics: 'pigeons' },
  { name: 'Little & Brown',    topics: 'sparrows' },
  { name: 'Tiny Singers',      topics: 'wrens' },
  { name: 'Shiny Collectors',  topics: 'magpies' },
  { name: 'Blue & Bold',       topics: 'jays' },
  { name: 'Small & Colourful', topics: 'finches' },
  { name: 'Yellow Song',       topics: 'canaries' },
  { name: 'Peace Symbol',      topics: 'doves' },
  { name: 'Circling Above',    topics: 'vultures' },
  { name: 'Head in the Sand',  topics: 'ostriches' },
  { name: 'Outback Runners',   topics: 'emus' },
  { name: 'Flightless & Fuzzy', topics: 'kiwis' },
  { name: "Nature's Oddity",  topics: 'platypus' },
  { name: 'Armoured Rollers',  topics: 'armadillos' },
  { name: 'Quill Defence',     topics: 'porcupines' },
  { name: 'Standing Watch',    topics: 'meerkats' },
  { name: 'Ringed Tails',      topics: 'lemurs' },
  { name: 'Desert Ships',      topics: 'camels' },
  { name: 'Fluffy & Spitting', topics: 'llamas' },
  { name: 'Softer Cousins',    topics: 'alpacas' },
  { name: 'Sure Footed',       topics: 'goats' },
  { name: 'Woolly Flock',      topics: 'sheep' },
  { name: 'Moo & Graze',       topics: 'cows' },
  { name: 'Mud & Oink',        topics: 'pigs' },
  { name: 'Coop & Cluck',      topics: 'chickens' },
  { name: 'Waddle & Quack',    topics: 'ducks' },
  { name: 'Gobble Gobble',     topics: 'gobbling' },
  { name: 'Stubborn Carriers', topics: 'donkeys' },
  { name: 'Twitchy Noses',     topics: 'rabbits' },
  { name: 'Wheel Runners',     topics: 'hamsters' },
  { name: 'Squeaking Pets',    topics: 'guinea' },
  { name: 'Bowl Swimmers',     topics: 'goldfish' },
  { name: 'Chatty Cages',      topics: 'parakeets' },
  { name: 'Carrying Their Home', topics: 'tortoises' },
  { name: 'Wall Walkers',      topics: 'geckos' },
  { name: 'Basking Lazily',    topics: 'iguanas' },
  { name: 'Smiling Swimmers',  topics: 'axolotls' },
  { name: 'Damp & Spotted',    topics: 'salamanders' },
  { name: 'Tiny & Amphibious', topics: 'newts' },
  // Extra themes 466-565
  { name: 'Glowing Gas Clouds', topics: 'nebulae' },
  { name: 'What Goes Up',      topics: 'gravity' },
  { name: 'Eyes in the Sky',   topics: 'satellites' },
  { name: 'Countdown to Launch', topics: 'rockets' },
  { name: 'The Red Planet',    topics: 'mars' },
  { name: 'The Gas Giant',     topics: 'jupiter' },
  { name: 'Ringed Beauty',     topics: 'saturn' },
  { name: 'Island Universes',  topics: 'galaxies' },
  { name: 'Looking Far Away',  topics: 'telescopes' },
  { name: 'Suited for Space',  topics: 'astronauts' },
  { name: 'Shiny Coating',     topics: 'glazing' },
  { name: 'Chiselled Form',    topics: 'sculpture' },
  { name: 'Tiny Tiles',        topics: 'mosaics' },
  { name: 'Light Through Colour', topics: 'stained' },
  { name: 'Beautiful Writing', topics: 'calligraphy' },
  { name: 'Ink & Press',       topics: 'printmaking' },
  { name: 'Over & Under',      topics: 'weaving' },
  { name: 'Patch by Patch',    topics: 'quilting' },
  { name: 'Needle & Thread',   topics: 'embroidery' },
  { name: 'Shavings & Grain',  topics: 'woodcarving' },
  { name: 'Hammer & Anvil',    topics: 'blacksmithing' },
  { name: 'Breath & Molten',   topics: 'glassblowing' },
  { name: 'Stitched & Tooled', topics: 'leatherwork' },
  { name: 'Woven Reeds',       topics: 'basketry' },
  { name: 'Melt & Pour',       topics: 'wax' },
  { name: 'Lather & Rinse',    topics: 'soap' },
  { name: 'Hops & Barley',     topics: 'brewing' },
  { name: 'Copper & Steam',    topics: 'distilling' },
  { name: 'Better with Time',  topics: 'aging' },
  { name: 'Wild Starter',      topics: 'sourdough' },
  { name: 'Rolled & Shaped',   topics: 'pasta' },
  { name: 'Raw & Rolled',      topics: 'sushi' },
  { name: 'Spiced & Simmered', topics: 'curry' },
  { name: 'Folded & Filled',   topics: 'tacos' },
  { name: 'Dough & Toppings',  topics: 'pizza' },
  { name: 'Steamed Parcels',   topics: 'dumplings' },
  { name: 'Noodle Soup',       topics: 'ramen' },
  { name: 'Low & Slow',        topics: 'ribs' },
  { name: 'Grid Marks',        topics: 'waffles' },
  { name: 'Flipped & Flat',    topics: 'pancakes' },
  { name: 'Morning Brew',      topics: 'coffee' },
  { name: 'Steeped Leaves',    topics: 'tea' },
  { name: 'Whirring Blades',   topics: 'blending' },
  { name: 'Shaken & Stirred',  topics: 'cocktails' },
  { name: 'Rows of Vines',     topics: 'vineyards' },
  { name: 'Pressed & Golden',  topics: 'olives' },
  { name: 'Keeper of the Hive', topics: 'beekeeping' },
  { name: 'Sealed in Jars',    topics: 'jam' },
  { name: 'Vinegar & Salt',    topics: 'pickling' },
  { name: 'Smoke & Salt',      topics: 'curing' },
  { name: 'Chains & Planks',   topics: 'drawbridge' },
  { name: 'Spires & Stone',    topics: 'cathedrals' },
  { name: 'Pointed to the Sky', topics: 'pyramids' },
  { name: 'Fight to the Death', topics: 'gladiators' },
  { name: 'The Great Wall',    topics: 'china' },
  { name: 'Sacred Places',     topics: 'temples' },
  { name: 'Throne Rooms',      topics: 'palaces' },
  { name: 'Guiding Ships Home', topics: 'beacons' },
  { name: 'Turning Blades',    topics: 'windmills' },
  { name: 'Carrying Water',    topics: 'aqueducts' },
  { name: 'Touching the Clouds', topics: 'skyscrapers' },
  { name: 'Curved Ceilings',   topics: 'domes' },
  { name: 'Holding it Up',     topics: 'columns' },
  { name: 'Carved from Rock',  topics: 'stone' },
  { name: 'Keep Them Out',     topics: 'defence' },
  { name: 'Dizzy Looking Down', topics: 'heights' },
  { name: 'Drilling Through',  topics: 'boring' },
  { name: 'Narrow Waterways',  topics: 'canals' },
  { name: 'Safe Port',         topics: 'harbours' },
  { name: 'Runways & Gates',   topics: 'airports' },
  { name: 'Tracks & Signals',  topics: 'railways' },
  { name: 'Crushing Depth',    topics: 'pressure' },
  { name: 'Spinning Blades Above', topics: 'helicopters' },
  { name: 'Woven & Carried',   topics: 'baskets' },
  { name: 'No Engine Needed',  topics: 'gliders' },
  { name: 'Pulling the Cord',  topics: 'parachutes' },
  { name: 'Kick & Ride',       topics: 'scooters' },
  { name: 'Two Wheels & Thunder', topics: 'motorcycles' },
  { name: 'Heavy Haulers',     topics: 'trucks' },
  { name: 'Ploughing Fields',  topics: 'tractors' },
  { name: 'Lifting High',      topics: 'cranes' },
  { name: 'Pushing Earth',     topics: 'bulldozers' },
  { name: 'Digging Deep',      topics: 'excavators' },
  { name: 'Lifting Pallets',   topics: 'forklifts' },
  { name: 'Assembly Lines',    topics: 'factories' },
  { name: 'Teeth & Turning',   topics: 'gears' },
  { name: 'Coiled Energy',     topics: 'springs' },
  { name: 'Ropes & Wheels',    topics: 'pulleys' },
  { name: 'Pivot & Push',      topics: 'levers' },
  { name: 'Invisible Pull',    topics: 'magnets' },
  { name: 'Stored Power',      topics: 'batteries' },
  { name: 'Wires & Flow',      topics: 'circuits' },
  { name: 'Focused Beams',     topics: 'lasers' },
  { name: 'Perfect Reflection', topics: 'mirrors' },
  { name: 'Splitting Light',   topics: 'prisms' },
  { name: 'Bending Light',     topics: 'lenses' },
  { name: 'Tiny Worlds',       topics: 'microscopes' },
  { name: 'Code of Life',      topics: 'genetics' },
  { name: 'Layers of Time',    topics: 'sediment' },
  { name: 'Growing Slowly',    topics: 'crystals' },
  // Extra themes 566-665
  { name: 'Glowing Underground', topics: 'magma' },
  { name: 'Shifting Plates',   topics: 'tectonic' },
  { name: 'Shooting Steam',    topics: 'geysers' },
  { name: "Nature's Hot Tub", topics: 'thermal' },
  { name: 'Falling Gracefully', topics: 'cascading' },
  { name: 'Floating Mountains', topics: 'icebergs' },
  { name: 'Tiny Builders',     topics: 'polyps' },
  { name: 'Underwater Forest', topics: 'kelp' },
  { name: 'Tangled Roots',     topics: 'mangroves' },
  { name: 'Soggy Ground',      topics: 'wetlands' },
  { name: 'Dry & Golden',      topics: 'savannas' },
  { name: 'Frozen Flat',       topics: 'tundra' },
  { name: 'Evergreen North',   topics: 'taiga' },
  { name: 'Endless Grasslands', topics: 'steppes' },
  { name: 'Water in the Desert', topics: 'oases' },
  { name: 'Carved by Ice',     topics: 'fjords' },
  { name: 'Ring of Sand',      topics: 'atolls' },
  { name: 'Spreading Out',     topics: 'deltas' },
  { name: 'Deep & Narrow',     topics: 'canyons' },
  { name: 'Flat on Top',       topics: 'plateaus' },
  { name: 'Black & White Battles', topics: 'chess' },
  { name: 'Shuffle & Deal',    topics: 'cards' },
  { name: 'Roll of Fate',      topics: 'dice' },
  { name: 'Move Your Piece',   topics: 'tokens' },
  { name: 'Spots & Chains',    topics: 'dominoes' },
  { name: 'Triple Twenty',     topics: 'darts' },
  { name: 'Cue & Pocket',      topics: 'billiards' },
  { name: 'Pins & Lanes',      topics: 'bowling' },
  { name: 'Love & Deuce',      topics: 'tennis' },
  { name: 'Fairway & Green',   topics: 'golf' },
  { name: 'Bat & Wicket',      topics: 'cricket' },
  { name: 'Scrum & Try',       topics: 'rugby' },
  { name: 'Gloves & Ring',     topics: 'boxing' },
  { name: 'Hold & Pin',        topics: 'wrestling' },
  { name: 'Thrust & Parry',    topics: 'fencing' },
  { name: 'Flips & Balance',   topics: 'gymnastics' },
  { name: 'Springboard Splash', topics: 'platforms' },
  { name: 'Pull & Glide',      topics: 'oars' },
  { name: 'Zig Zag Course',    topics: 'tacking' },
  { name: 'Powder & Speed',    topics: 'skiing' },
  { name: 'Stones & Brooms',   topics: 'curling' },
  { name: 'Puck & Stick',      topics: 'hockey' },
  { name: 'Dribble & Dunk',    topics: 'basketball' },
  { name: 'Diamond & Bat',     topics: 'baseball' },
  { name: 'Touchdown',         topics: 'football' },
  { name: 'Beautiful Game',    topics: 'soccer' },
  { name: 'Feathered & Fast',  topics: 'badminton' },
  { name: 'Tiny Table',        topics: 'paddles' },
  { name: 'Four Walls',        topics: 'squash' },
  { name: 'Chalk & Grip',      topics: 'climbing' },
  { name: 'Black & White Keys', topics: 'piano' },
  { name: 'Six Strings',       topics: 'guitar' },
  { name: 'Beat & Crash',      topics: 'drums' },
  { name: 'Bowed & Beautiful', topics: 'violin' },
  { name: 'Silver & Blown',    topics: 'flute' },
  { name: 'Brass & Bold',      topics: 'trumpet' },
  { name: 'Smooth & Jazz',     topics: 'saxophone' },
  { name: 'Plucked Strings',   topics: 'harp' },
  { name: 'Deep & Rich',       topics: 'cello' },
  { name: 'Highland Sound',    topics: 'bagpipes' },
  { name: 'Grand Voices',      topics: 'opera' },
  { name: 'On Pointe',         topics: 'ballet' },
  { name: 'Feel the Beat',     topics: 'rhythm' },
  { name: 'Hot Steps',         topics: 'salsa' },
  { name: 'One Two Three',     topics: 'waltz' },
  { name: 'Spinning on the Floor', topics: 'breakdancing' },
  { name: 'Pulled by Strings', topics: 'puppets' },
  { name: 'Big Top',           topics: 'circus' },
  { name: 'Now You See It',    topics: 'magic' },
  { name: 'Keeping it Up',     topics: 'juggling' },
  { name: 'Red Nose',          topics: 'clowns' },
  { name: 'Hidden Faces',      topics: 'masks' },
  { name: 'Silent Performance', topics: 'mime' },
  { name: 'Verse & Rhyme',     topics: 'poetry' },
  { name: 'Between the Covers', topics: 'novels' },
  { name: 'Panels & Speech Bubbles', topics: 'comics' },
  { name: 'Hot Off the Press', topics: 'newspapers' },
  { name: 'Charted Territory', topics: 'maps' },
  { name: 'Finding North',     topics: 'compasses' },
  { name: 'Shadow Time',       topics: 'sundials' },
  { name: 'Sands of Time',     topics: 'hourglasses' },
  { name: 'Swinging Weight',   topics: 'pendulums' },
  { name: 'Mercury Rising',    topics: 'thermometers' },
  { name: 'Reading the Air',   topics: 'barometers' },
  { name: 'Pointing the Way',  topics: 'windvanes' },
  { name: 'Shadow Stick',      topics: 'gnomon' },
  { name: 'Counting Beads',    topics: 'abacus' },
  { name: 'Click Clack Keys',  topics: 'typewriters' },
  { name: 'Dots & Dashes',     topics: 'telegraphs' },
  { name: 'Tuning In',         topics: 'radios' },
  { name: 'Grooves & Needles', topics: 'vinyl' },
  { name: 'Click & Flash',     topics: 'cameras' },
  { name: 'Reels of Light',    topics: 'projectors' },
  { name: 'Bright Idea',       topics: 'lightbulbs' },
  { name: 'Pumping Power',     topics: 'pistons' },
  { name: 'Ticking Inside',    topics: 'clockwork' },
  { name: 'Movable Type',      topics: 'printing' },
  { name: 'Round & Round',     topics: 'spinning' },
  { name: 'Shuttle & Warp',    topics: 'looms' },
  { name: 'Strike While Hot',  topics: 'anvils' },
  { name: 'Fanning the Flames', topics: 'bellows' },
];
