// 665 themes for Span.IT — cycles through all available themes
// Each theme has a display name and Datamuse API topics string
export const THEMES = [
  // January (31)
  { name: 'Ocean Life',             topics: 'ocean,sea,marine' },
  { name: 'Space Exploration',      topics: 'space,astronomy,cosmos' },
  { name: 'Cooking & Food',         topics: 'cooking,food,cuisine' },
  { name: 'Ancient History',        topics: 'ancient,history,civilization' },
  { name: 'Music',                  topics: 'music,melody,rhythm' },
  { name: 'Weather & Climate',      topics: 'weather,climate,atmosphere' },
  { name: 'Sports',                 topics: 'sports,athletics,competition' },
  { name: 'Technology',             topics: 'technology,computers,software' },
  { name: 'Animals',                topics: 'animals,wildlife,creatures' },
  { name: 'Architecture',           topics: 'architecture,buildings,construction' },
  { name: 'Human Body',             topics: 'anatomy,body,medicine' },
  { name: 'Travel & Adventure',     topics: 'travel,adventure,exploration' },
  { name: 'Art & Creativity',       topics: 'art,painting,creativity' },
  { name: 'Science',                topics: 'science,chemistry,physics' },
  { name: 'Mythology',              topics: 'mythology,legends,gods' },
  { name: 'Fashion & Style',        topics: 'fashion,clothing,style' },
  { name: 'Gardening & Plants',     topics: 'plants,gardening,nature' },
  { name: 'Film & Cinema',          topics: 'film,cinema,movies' },
  { name: 'Mathematics',            topics: 'mathematics,geometry,numbers' },
  { name: 'Languages & Words',      topics: 'language,linguistics,words' },
  { name: 'Forests & Trees',        topics: 'forest,trees,woodland' },
  { name: 'Insects & Bugs',         topics: 'insects,bugs,entomology' },
  { name: 'Emotions & Feelings',    topics: 'emotions,feelings,psychology' },
  { name: 'Geography',              topics: 'geography,countries,continents' },
  { name: 'Dinosaurs',              topics: 'dinosaurs,prehistoric,fossils' },
  { name: 'Farming & Agriculture',  topics: 'farming,agriculture,crops' },
  { name: 'Medicine & Health',      topics: 'medicine,health,healing' },
  { name: 'Superheroes',            topics: 'superheroes,comics,powers' },
  { name: 'Astronomy',              topics: 'stars,planets,telescope' },
  { name: 'Folklore & Legends',     topics: 'folklore,legends,myths' },
  { name: 'Winter & Snow',          topics: 'winter,snow,cold' },
  // February (28)
  { name: 'Love & Romance',         topics: 'love,romance,relationships' },
  { name: 'Chocolate & Sweets',     topics: 'chocolate,sweets,candy' },
  { name: 'Birds',                  topics: 'birds,avian,feathers' },
  { name: 'Oceans & Seas',          topics: 'oceans,seas,tides' },
  { name: 'Volcanoes & Geology',    topics: 'volcanoes,geology,rocks' },
  { name: 'Photography',            topics: 'photography,camera,images' },
  { name: 'Dance & Movement',       topics: 'dance,movement,choreography' },
  { name: 'Reptiles',               topics: 'reptiles,lizards,snakes' },
  { name: 'Bread & Baking',         topics: 'bread,baking,pastry' },
  { name: 'Castles & Fortresses',   topics: 'castles,fortresses,medieval' },
  { name: 'Clouds & Sky',           topics: 'clouds,sky,atmosphere' },
  { name: 'Robots & AI',            topics: 'robots,artificial intelligence,automation' },
  { name: 'Gems & Minerals',        topics: 'gems,minerals,crystals' },
  { name: 'Theatre & Drama',        topics: 'theatre,drama,performance' },
  { name: 'Deserts',                topics: 'desert,sand,arid' },
  { name: 'Fishing',                topics: 'fishing,angling,fish' },
  { name: 'Horses & Riding',        topics: 'horses,riding,equestrian' },
  { name: 'Bridges & Engineering',  topics: 'bridges,engineering,structures' },
  { name: 'Cheese & Dairy',         topics: 'cheese,dairy,milk' },
  { name: 'Caves & Underground',    topics: 'caves,underground,spelunking' },
  { name: 'Yoga & Meditation',      topics: 'yoga,meditation,mindfulness' },
  { name: 'Trains & Railways',      topics: 'trains,railways,locomotives' },
  { name: 'Flowers',                topics: 'flowers,blooms,petals' },
  { name: 'Puzzles & Games',        topics: 'puzzles,games,riddles' },
  { name: 'Camping & Outdoors',     topics: 'camping,outdoors,hiking' },
  { name: 'Sharks',                 topics: 'sharks,predators,ocean' },
  { name: 'Colours & Pigments',     topics: 'colours,pigments,hues' },
  { name: 'Clocks & Time',          topics: 'clocks,time,horology' },
  // March (31)
  { name: 'Spring & Renewal',       topics: 'spring,renewal,growth' },
  { name: 'Frogs & Amphibians',     topics: 'frogs,amphibians,wetlands' },
  { name: 'Sailing & Ships',        topics: 'sailing,ships,nautical' },
  { name: 'Cheese Making',          topics: 'fermentation,cheese,culture' },
  { name: 'Rainforests',            topics: 'rainforest,tropical,jungle' },
  { name: 'Cycling',                topics: 'cycling,bicycle,racing' },
  { name: 'Pottery & Ceramics',     topics: 'pottery,ceramics,clay' },
  { name: 'Storms & Lightning',     topics: 'storms,lightning,thunder' },
  { name: 'Cats',                   topics: 'cats,felines,kittens' },
  { name: 'Dogs',                   topics: 'dogs,canines,puppies' },
  { name: 'Bread & Grains',         topics: 'bread,grains,wheat' },
  { name: 'Volcanoes',              topics: 'volcanoes,lava,eruption' },
  { name: 'Martial Arts',           topics: 'martial arts,combat,fighting' },
  { name: 'Butterflies & Moths',    topics: 'butterflies,moths,insects' },
  { name: 'Cheese & Wine',          topics: 'wine,grapes,vineyard' },
  { name: 'Robots',                 topics: 'robots,machines,automation' },
  { name: 'Coral Reefs',            topics: 'coral,reef,marine' },
  { name: 'Hiking & Mountains',     topics: 'hiking,mountains,trails' },
  { name: 'Bees & Honey',           topics: 'bees,honey,pollination' },
  { name: 'Libraries & Books',      topics: 'libraries,books,reading' },
  { name: 'Submarines',             topics: 'submarines,underwater,navy' },
  { name: 'Spices & Herbs',         topics: 'spices,herbs,flavors' },
  { name: 'Archaeology',            topics: 'archaeology,excavation,artifacts' },
  { name: 'Surfing',                topics: 'surfing,waves,beach' },
  { name: 'Mushrooms & Fungi',      topics: 'mushrooms,fungi,spores' },
  { name: 'Astronomy & Stars',      topics: 'astronomy,stars,constellations' },
  { name: 'Knitting & Weaving',     topics: 'knitting,weaving,textiles' },
  { name: 'Frogs',                  topics: 'frogs,toads,amphibians' },
  { name: 'Cheese',                 topics: 'cheese,dairy,curd' },
  { name: 'Kites & Wind',           topics: 'kites,wind,flying' },
  { name: 'Eggs & Hatching',        topics: 'eggs,hatching,birds' },
  // April (30)
  { name: 'Rain & Puddles',         topics: 'rain,puddles,water' },
  { name: 'Frogs & Ponds',          topics: 'ponds,frogs,wetlands' },
  { name: 'Gardening',              topics: 'gardening,seeds,soil' },
  { name: 'Chocolate',              topics: 'chocolate,cocoa,sweets' },
  { name: 'Astronomy',              topics: 'planets,moons,orbits' },
  { name: 'Painting & Colours',     topics: 'painting,colours,canvas' },
  { name: 'Snakes',                 topics: 'snakes,reptiles,venom' },
  { name: 'Bridges',                topics: 'bridges,spans,engineering' },
  { name: 'Cheese & Crackers',      topics: 'crackers,snacks,cheese' },
  { name: 'Clouds',                 topics: 'clouds,cumulus,stratus' },
  { name: 'Origami',                topics: 'origami,paper,folding' },
  { name: 'Whales',                 topics: 'whales,cetaceans,ocean' },
  { name: 'Bread',                  topics: 'bread,loaves,yeast' },
  { name: 'Castles',                topics: 'castles,towers,moats' },
  { name: 'Butterflies',            topics: 'butterflies,wings,metamorphosis' },
  { name: 'Sailing',                topics: 'sailing,boats,wind' },
  { name: 'Volcanoes & Lava',       topics: 'lava,magma,eruption' },
  { name: 'Yoga',                   topics: 'yoga,poses,breathing' },
  { name: 'Trains',                 topics: 'trains,stations,tracks' },
  { name: 'Flowers & Blooms',       topics: 'flowers,blooms,spring' },
  { name: 'Puzzles',                topics: 'puzzles,jigsaws,riddles' },
  { name: 'Camping',                topics: 'camping,tents,wilderness' },
  { name: 'Sharks & Rays',          topics: 'sharks,rays,cartilage' },
  { name: 'Colours',                topics: 'colours,spectrum,rainbow' },
  { name: 'Clocks',                 topics: 'clocks,watches,time' },
  { name: 'Bees',                   topics: 'bees,hives,nectar' },
  { name: 'Libraries',              topics: 'libraries,shelves,books' },
  { name: 'Spices',                 topics: 'spices,pepper,cinnamon' },
  { name: 'Archaeology & Ruins',    topics: 'ruins,archaeology,ancient' },
  { name: 'Surfing & Waves',        topics: 'surfing,waves,ocean' },
  // May (31)
  { name: 'Blossom & Spring',       topics: 'blossom,spring,flowers' },
  { name: 'Honey & Bees',           topics: 'honey,bees,hive' },
  { name: 'Frogs & Tadpoles',       topics: 'tadpoles,frogs,pond' },
  { name: 'Cycling & Bikes',        topics: 'cycling,bikes,pedals' },
  { name: 'Pottery',                topics: 'pottery,clay,kiln' },
  { name: 'Storms',                 topics: 'storms,thunder,lightning' },
  { name: 'Cats & Kittens',         topics: 'cats,kittens,felines' },
  { name: 'Dogs & Puppies',         topics: 'dogs,puppies,canines' },
  { name: 'Grains & Cereals',       topics: 'grains,cereals,wheat' },
  { name: 'Martial Arts',           topics: 'karate,judo,combat' },
  { name: 'Coral & Reefs',          topics: 'coral,reefs,polyps' },
  { name: 'Mountain Hiking',        topics: 'mountains,hiking,altitude' },
  { name: 'Submarines & Diving',    topics: 'submarines,diving,depth' },
  { name: 'Herbs & Spices',         topics: 'herbs,spices,seasoning' },
  { name: 'Archaeology & Digs',     topics: 'digs,archaeology,fossils' },
  { name: 'Surfing & Beaches',      topics: 'surfing,beaches,waves' },
  { name: 'Mushrooms',              topics: 'mushrooms,fungi,forest' },
  { name: 'Knitting',               topics: 'knitting,yarn,needles' },
  { name: 'Eggs',                   topics: 'eggs,shells,yolk' },
  { name: 'Kites',                  topics: 'kites,wind,string' },
  { name: 'Rain & Storms',          topics: 'rain,storms,thunder' },
  { name: 'Ponds & Lakes',          topics: 'ponds,lakes,freshwater' },
  { name: 'Chocolate & Cocoa',      topics: 'chocolate,cocoa,cacao' },
  { name: 'Planets & Moons',        topics: 'planets,moons,solar system' },
  { name: 'Painting',               topics: 'painting,brushes,canvas' },
  { name: 'Snakes & Lizards',       topics: 'snakes,lizards,reptiles' },
  { name: 'Origami & Paper',        topics: 'origami,paper,folding' },
  { name: 'Whales & Dolphins',      topics: 'whales,dolphins,cetaceans' },
  { name: 'Bread & Yeast',          topics: 'bread,yeast,dough' },
  { name: 'Castles & Knights',      topics: 'castles,knights,medieval' },
  { name: 'Butterflies & Flowers',  topics: 'butterflies,flowers,nectar' },
  // June (30)
  { name: 'Summer & Sun',           topics: 'summer,sun,heat' },
  { name: 'Swimming & Pools',       topics: 'swimming,pools,water' },
  { name: 'Ice Cream & Gelato',     topics: 'ice cream,gelato,frozen' },
  { name: 'Festivals & Fairs',      topics: 'festivals,fairs,celebrations' },
  { name: 'Camping & Fires',        topics: 'camping,campfire,outdoors' },
  { name: 'Sailing & Yachts',       topics: 'sailing,yachts,marina' },
  { name: 'Sunflowers',             topics: 'sunflowers,seeds,yellow' },
  { name: 'Barbecue & Grilling',    topics: 'barbecue,grilling,smoke' },
  { name: 'Beaches & Sand',         topics: 'beaches,sand,shore' },
  { name: 'Fireflies & Night',      topics: 'fireflies,night,glow' },
  { name: 'Strawberries & Berries', topics: 'strawberries,berries,fruit' },
  { name: 'Hiking & Trails',        topics: 'hiking,trails,backpacking' },
  { name: 'Astronomy & Solstice',   topics: 'solstice,astronomy,sun' },
  { name: 'Frisbee & Outdoor Games',topics: 'frisbee,outdoor,games' },
  { name: 'Tropical Fish',          topics: 'tropical,fish,aquarium' },
  { name: 'Lemonade & Drinks',      topics: 'lemonade,drinks,refreshing' },
  { name: 'Butterflies & Gardens',  topics: 'butterflies,gardens,flowers' },
  { name: 'Volleyball & Beach',     topics: 'volleyball,beach,sports' },
  { name: 'Picnics & Parks',        topics: 'picnics,parks,outdoors' },
  { name: 'Rainbows',               topics: 'rainbows,colours,light' },
  { name: 'Crabs & Lobsters',       topics: 'crabs,lobsters,crustaceans' },
  { name: 'Sunsets & Horizons',     topics: 'sunsets,horizons,sky' },
  { name: 'Watermelons & Fruit',    topics: 'watermelons,fruit,summer' },
  { name: 'Sandcastles',            topics: 'sandcastles,sand,beach' },
  { name: 'Hammocks & Relaxing',    topics: 'hammocks,relaxing,leisure' },
  { name: 'Seashells',              topics: 'seashells,shells,beach' },
  { name: 'Lighthouses',            topics: 'lighthouses,coast,navigation' },
  { name: 'Turtles & Tortoises',    topics: 'turtles,tortoises,reptiles' },
  { name: 'Mangoes & Tropics',      topics: 'mangoes,tropical,fruit' },
  { name: 'Kayaking & Canoeing',    topics: 'kayaking,canoeing,paddling' },
  // July (31)
  { name: 'Fireworks & Celebrations', topics: 'fireworks,celebrations,festivals' },
  { name: 'Hot Air Balloons',       topics: 'balloons,flight,sky' },
  { name: 'Deserts & Dunes',        topics: 'deserts,dunes,sand' },
  { name: 'Parrots & Tropical Birds', topics: 'parrots,tropical,birds' },
  { name: 'Surfboards & Waves',     topics: 'surfboards,waves,surfing' },
  { name: 'Coconuts & Palms',       topics: 'coconuts,palms,tropical' },
  { name: 'Snorkelling & Diving',   topics: 'snorkelling,diving,reef' },
  { name: 'Waterparks & Slides',    topics: 'waterparks,slides,water' },
  { name: 'Ants & Colonies',        topics: 'ants,colonies,insects' },
  { name: 'Sunscreen & Skin',       topics: 'sunscreen,skin,protection' },
  { name: 'Pineapples & Tropics',   topics: 'pineapples,tropical,fruit' },
  { name: 'Skateboarding',          topics: 'skateboarding,tricks,ramps' },
  { name: 'Astronomy & Comets',     topics: 'comets,asteroids,space' },
  { name: 'Sandals & Footwear',     topics: 'sandals,footwear,summer' },
  { name: 'Jellyfish',              topics: 'jellyfish,tentacles,ocean' },
  { name: 'Hammers & Tools',        topics: 'hammers,tools,carpentry' },
  { name: 'Lava Lamps & Retro',     topics: 'retro,vintage,nostalgia' },
  { name: 'Frogs & Lily Pads',      topics: 'frogs,lily pads,pond' },
  { name: 'Treasure & Pirates',     topics: 'treasure,pirates,gold' },
  { name: 'Mangoes & Papayas',      topics: 'mangoes,papayas,tropical' },
  { name: 'Cycling & Tours',        topics: 'cycling,tours,racing' },
  { name: 'Archery',                topics: 'archery,arrows,bows' },
  { name: 'Dolphins & Porpoises',   topics: 'dolphins,porpoises,marine' },
  { name: 'Hammocks & Shade',       topics: 'hammocks,shade,relaxing' },
  { name: 'Crabs & Tides',          topics: 'crabs,tides,shore' },
  { name: 'Sunflowers & Fields',    topics: 'sunflowers,fields,yellow' },
  { name: 'Kayaking & Rivers',      topics: 'kayaking,rivers,rapids' },
  { name: 'Seagulls & Coasts',      topics: 'seagulls,coasts,birds' },
  { name: 'Watermelons',            topics: 'watermelons,seeds,summer' },
  { name: 'Sandcastles & Moats',    topics: 'sandcastles,moats,beach' },
  { name: 'Lighthouses & Fog',      topics: 'lighthouses,fog,coast' },
  // August (31)
  { name: 'Back to School',         topics: 'school,education,learning' },
  { name: 'Harvest & Crops',        topics: 'harvest,crops,farming' },
  { name: 'Sunsets & Dusk',         topics: 'sunsets,dusk,twilight' },
  { name: 'Camping & Stars',        topics: 'camping,stars,night' },
  { name: 'Corn & Maize',           topics: 'corn,maize,harvest' },
  { name: 'Dragonflies',            topics: 'dragonflies,insects,ponds' },
  { name: 'Peaches & Plums',        topics: 'peaches,plums,stone fruit' },
  { name: 'Rowing & Regattas',      topics: 'rowing,regattas,boats' },
  { name: 'Astronomy & Meteors',    topics: 'meteors,shooting stars,sky' },
  { name: 'Grasshoppers & Crickets',topics: 'grasshoppers,crickets,insects' },
  { name: 'Sunflower Seeds',        topics: 'seeds,sunflowers,harvest' },
  { name: 'Skateparks',             topics: 'skateparks,ramps,tricks' },
  { name: 'Tomatoes & Vegetables',  topics: 'tomatoes,vegetables,garden' },
  { name: 'Sailing & Regattas',     topics: 'sailing,regattas,racing' },
  { name: 'Bats & Nocturnal',       topics: 'bats,nocturnal,night' },
  { name: 'Lavender & Herbs',       topics: 'lavender,herbs,fragrance' },
  { name: 'Cycling & Mountains',    topics: 'cycling,mountains,altitude' },
  { name: 'Crabs & Rockpools',      topics: 'crabs,rockpools,shore' },
  { name: 'Figs & Dates',           topics: 'figs,dates,fruit' },
  { name: 'Archery & Targets',      topics: 'archery,targets,precision' },
  { name: 'Dolphins & Surfing',     topics: 'dolphins,surfing,ocean' },
  { name: 'Hammers & Nails',        topics: 'hammers,nails,carpentry' },
  { name: 'Treasure Maps',          topics: 'treasure maps,pirates,adventure' },
  { name: 'Mangoes & Smoothies',    topics: 'mangoes,smoothies,blending' },
  { name: 'Frogs & Croaking',       topics: 'frogs,croaking,night' },
  { name: 'Seashells & Collecting', topics: 'seashells,collecting,beach' },
  { name: 'Jellyfish & Plankton',   topics: 'jellyfish,plankton,ocean' },
  { name: 'Sandcastles & Waves',    topics: 'sandcastles,waves,beach' },
  { name: 'Lighthouses & Ships',    topics: 'lighthouses,ships,navigation' },
  { name: 'Turtles & Nesting',      topics: 'turtles,nesting,beach' },
  { name: 'Kayaking & Waterfalls',  topics: 'kayaking,waterfalls,rivers' },
  // September (30)
  { name: 'Autumn & Leaves',        topics: 'autumn,leaves,fall' },
  { name: 'Apples & Orchards',      topics: 'apples,orchards,harvest' },
  { name: 'Spiders & Webs',         topics: 'spiders,webs,arachnids' },
  { name: 'Pumpkins & Gourds',      topics: 'pumpkins,gourds,harvest' },
  { name: 'Acorns & Squirrels',     topics: 'acorns,squirrels,nuts' },
  { name: 'Mushrooms & Foraging',   topics: 'mushrooms,foraging,forest' },
  { name: 'Harvest Moon',           topics: 'harvest moon,autumn,sky' },
  { name: 'Cider & Apples',         topics: 'cider,apples,fermentation' },
  { name: 'Hedgehogs',              topics: 'hedgehogs,spines,nocturnal' },
  { name: 'Conkers & Chestnuts',    topics: 'conkers,chestnuts,autumn' },
  { name: 'Fog & Mist',             topics: 'fog,mist,atmosphere' },
  { name: 'Owls & Night',           topics: 'owls,night,hunting' },
  { name: 'Grapes & Vineyards',     topics: 'grapes,vineyards,harvest' },
  { name: 'Scarecrows & Fields',    topics: 'scarecrows,fields,farming' },
  { name: 'Deer & Stags',           topics: 'deer,stags,antlers' },
  { name: 'Pears & Quinces',        topics: 'pears,quinces,fruit' },
  { name: 'Cobwebs & Spiders',      topics: 'cobwebs,spiders,silk' },
  { name: 'Walnuts & Hazelnuts',    topics: 'walnuts,hazelnuts,nuts' },
  { name: 'Geese & Migration',      topics: 'geese,migration,birds' },
  { name: 'Bonfires & Smoke',       topics: 'bonfires,smoke,fire' },
  { name: 'Foxes & Dens',           topics: 'foxes,dens,cunning' },
  { name: 'Pumpkin Carving',        topics: 'pumpkins,carving,halloween' },
  { name: 'Wool & Knitting',        topics: 'wool,knitting,yarn' },
  { name: 'Crows & Ravens',         topics: 'crows,ravens,black birds' },
  { name: 'Harvest Festivals',      topics: 'harvest,festivals,celebration' },
  { name: 'Badgers & Burrows',      topics: 'wildlife,burrows,mammals' },
  { name: 'Maple Syrup',            topics: 'maple,syrup,trees' },
  { name: 'Scarves & Coats',        topics: 'scarves,coats,autumn' },
  { name: 'Berries & Brambles',     topics: 'berries,brambles,foraging' },
  { name: 'Toadstools & Fungi',     topics: 'toadstools,fungi,forest' },
  // October (31)
  { name: 'Halloween & Ghosts',     topics: 'halloween,ghosts,spooky' },
  { name: 'Witches & Cauldrons',    topics: 'witches,cauldrons,magic' },
  { name: 'Pumpkins & Lanterns',    topics: 'pumpkins,lanterns,carving' },
  { name: 'Bats & Caves',           topics: 'bats,caves,nocturnal' },
  { name: 'Skeletons & Bones',      topics: 'skeletons,bones,anatomy' },
  { name: 'Spiders & Webs',         topics: 'spiders,webs,silk' },
  { name: 'Vampires & Castles',     topics: 'vampires,castles,gothic' },
  { name: 'Zombies & Horror',       topics: 'zombies,horror,undead' },
  { name: 'Candy & Trick or Treat', topics: 'candy,trick or treat,sweets' },
  { name: 'Autumn Colours',         topics: 'autumn,colours,leaves' },
  { name: 'Owls & Moonlight',       topics: 'owls,moonlight,night' },
  { name: 'Fog & Graveyards',       topics: 'fog,graveyards,eerie' },
  { name: 'Wolves & Howling',       topics: 'wolves,howling,moon' },
  { name: 'Potions & Magic',        topics: 'potions,magic,spells' },
  { name: 'Scarecrows',             topics: 'scarecrows,fields,straw' },
  { name: 'Crows & Omens',          topics: 'crows,omens,ravens' },
  { name: 'Haunted Houses',         topics: 'haunted,houses,ghosts' },
  { name: 'Mummies & Egypt',        topics: 'mummies,egypt,tombs' },
  { name: 'Black Cats',             topics: 'black cats,superstition,luck' },
  { name: 'Frankenstein & Monsters',topics: 'frankenstein,monsters,horror' },
  { name: 'Mazes & Labyrinths',     topics: 'mazes,labyrinths,puzzles' },
  { name: 'Fog & Mystery',          topics: 'fog,mystery,unknown' },
  { name: 'Cauldrons & Brews',      topics: 'cauldrons,brews,potions' },
  { name: 'Gargoyles & Gothic',     topics: 'gargoyles,gothic,architecture' },
  { name: 'Werewolves',             topics: 'werewolves,transformation,moon' },
  { name: 'Cobwebs & Dust',         topics: 'cobwebs,dust,abandoned' },
  { name: 'Lanterns & Candles',     topics: 'lanterns,candles,light' },
  { name: 'Autumn Harvest',         topics: 'harvest,autumn,abundance' },
  { name: 'Pumpkin Spice',          topics: 'pumpkin,spice,autumn' },
  { name: 'Costumes & Masks',       topics: 'costumes,masks,disguise' },
  { name: 'Candy Corn & Sweets',    topics: 'candy corn,sweets,halloween' },
  // November (30)
  { name: 'Bonfire Night',          topics: 'bonfires,fireworks,gunpowder' },
  { name: 'Remembrance & Poppies',  topics: 'poppies,remembrance,war' },
  { name: 'Fog & Frost',            topics: 'fog,frost,cold' },
  { name: 'Squirrels & Nuts',       topics: 'squirrels,nuts,hoarding' },
  { name: 'Thanksgiving & Feasts',  topics: 'thanksgiving,feasts,gratitude' },
  { name: 'Turkeys & Stuffing',     topics: 'turkeys,stuffing,roasting' },
  { name: 'Pies & Pastries',        topics: 'pies,pastries,baking' },
  { name: 'Scarves & Mittens',      topics: 'scarves,mittens,warmth' },
  { name: 'Deer & Antlers',         topics: 'deer,antlers,forest' },
  { name: 'Chestnuts & Fires',      topics: 'chestnuts,fires,roasting' },
  { name: 'Geese & Flocks',         topics: 'geese,flocks,migration' },
  { name: 'Hedgehogs & Hibernation',topics: 'hedgehogs,hibernation,winter' },
  { name: 'Soup & Stews',           topics: 'soup,stews,warming' },
  { name: 'Candles & Warmth',       topics: 'candles,warmth,light' },
  { name: 'Foxes & Forests',        topics: 'foxes,forests,cunning' },
  { name: 'Wool & Fleece',          topics: 'wool,fleece,warmth' },
  { name: 'Badgers & Setts',        topics: 'badgers,woodland,mammals' },
  { name: 'Mushrooms & Damp',       topics: 'mushrooms,damp,forest' },
  { name: 'Owls & Hunting',         topics: 'owls,hunting,silent' },
  { name: 'Berries & Hedgerows',    topics: 'berries,hedgerows,foraging' },
  { name: 'Crows & Ravens',         topics: 'crows,ravens,birds' },
  { name: 'Mud & Puddles',          topics: 'mud,puddles,rain' },
  { name: 'Fireside & Logs',        topics: 'fireside,logs,warmth' },
  { name: 'Weasels & Stoats',       topics: 'weasels,ferrets,mammals' },
  { name: 'Pumpkin Soup',           topics: 'pumpkin,soup,autumn' },
  { name: 'Starlings & Flocking',   topics: 'starlings,flocking,birds' },
  { name: 'Frost & Ice',            topics: 'frost,ice,freezing' },
  { name: 'Robins & Redbreasts',    topics: 'robins,redbreasts,winter' },
  { name: 'Pinecones & Firs',       topics: 'pinecones,firs,conifers' },
  { name: 'Mist & Valleys',         topics: 'mist,valleys,morning' },
  // December (31)
  { name: 'Christmas & Gifts',      topics: 'christmas,gifts,presents' },
  { name: 'Snow & Snowflakes',      topics: 'snow,snowflakes,winter' },
  { name: 'Reindeer & Sleighs',     topics: 'reindeer,sleighs,christmas' },
  { name: 'Elves & Workshops',      topics: 'elves,workshops,toys' },
  { name: 'Christmas Trees',        topics: 'christmas trees,decorations,ornaments' },
  { name: 'Candles & Advent',       topics: 'candles,advent,christmas' },
  { name: 'Gingerbread & Cookies',  topics: 'gingerbread,cookies,baking' },
  { name: 'Carols & Singing',       topics: 'carols,singing,christmas' },
  { name: 'Stockings & Fireplaces', topics: 'stockings,fireplaces,christmas' },
  { name: 'Snowmen & Scarves',      topics: 'snowmen,scarves,winter' },
  { name: 'Holly & Mistletoe',      topics: 'holly,mistletoe,christmas' },
  { name: 'Bells & Jingles',        topics: 'bells,jingles,christmas' },
  { name: 'Wrapping & Ribbons',     topics: 'wrapping,ribbons,gifts' },
  { name: 'Mulled Wine & Spices',   topics: 'mulled wine,spices,warmth' },
  { name: 'Polar Bears & Arctic',   topics: 'polar bears,arctic,ice' },
  { name: 'Penguins & Antarctica',  topics: 'penguins,antarctica,cold' },
  { name: 'Ice Skating',            topics: 'ice skating,rinks,winter' },
  { name: 'Snowboarding & Skiing',  topics: 'snowboarding,skiing,slopes' },
  { name: 'Yule & Traditions',      topics: 'yule,traditions,winter' },
  { name: 'Nutcrackers & Ballet',   topics: 'nutcrackers,ballet,christmas' },
  { name: 'Tinsel & Baubles',       topics: 'tinsel,baubles,decorations' },
  { name: 'Chestnuts & Roasting',   topics: 'chestnuts,roasting,fire' },
  { name: 'Eggnog & Drinks',        topics: 'eggnog,drinks,christmas' },
  { name: 'Wreath & Garlands',      topics: 'wreaths,garlands,christmas' },
  { name: 'Icicles & Frost',        topics: 'icicles,frost,winter' },
  { name: 'Boxing Day & Leftovers', topics: 'boxing day,leftovers,feasting' },
  { name: 'New Year & Fireworks',   topics: 'new year,fireworks,celebrations' },
  { name: 'Resolutions & Goals',    topics: 'resolutions,goals,new year' },
  { name: 'Champagne & Toasts',     topics: 'champagne,toasts,celebrations' },
  { name: 'Midnight & Clocks',      topics: 'midnight,clocks,new year' },
  { name: 'Winter Solstice',        topics: 'winter solstice,darkness,light' },
  // Extra themes 366-465
  { name: 'Glaciers & Ice',         topics: 'glaciers,ice,frozen' },
  { name: 'Wolves & Packs',         topics: 'wolves,packs,hunting' },
  { name: 'Eagles & Raptors',       topics: 'eagles,raptors,soaring' },
  { name: 'Caves & Stalactites',    topics: 'caves,stalactites,underground' },
  { name: 'Deserts & Cacti',        topics: 'deserts,cacti,arid' },
  { name: 'Rivers & Currents',      topics: 'rivers,currents,flowing' },
  { name: 'Volcanoes & Ash',        topics: 'volcanoes,ash,eruption' },
  { name: 'Tornadoes & Wind',       topics: 'tornadoes,wind,destruction' },
  { name: 'Earthquakes & Faults',   topics: 'earthquakes,faults,seismic' },
  { name: 'Tsunamis & Waves',       topics: 'tsunamis,waves,disaster' },
  { name: 'Penguins & Ice',         topics: 'penguins,ice,colony' },
  { name: 'Flamingos & Wetlands',   topics: 'flamingos,wetlands,pink' },
  { name: 'Elephants & Herds',      topics: 'elephants,herds,savanna' },
  { name: 'Lions & Pride',          topics: 'lions,pride,savanna' },
  { name: 'Giraffes & Savannas',    topics: 'giraffes,savannas,tall' },
  { name: 'Zebras & Stripes',       topics: 'zebras,stripes,plains' },
  { name: 'Gorillas & Jungles',     topics: 'gorillas,jungles,primates' },
  { name: 'Pandas & Bamboo',        topics: 'pandas,bamboo,china' },
  { name: 'Koalas & Eucalyptus',    topics: 'koalas,eucalyptus,australia' },
  { name: 'Kangaroos & Outback',    topics: 'kangaroos,outback,australia' },
  { name: 'Octopus & Tentacles',    topics: 'octopus,tentacles,deep sea' },
  { name: 'Seahorses & Coral',      topics: 'seahorses,coral,ocean' },
  { name: 'Starfish & Tides',       topics: 'starfish,tides,rockpool' },
  { name: 'Penguins & Fishing',     topics: 'penguins,fishing,antarctic' },
  { name: 'Owls & Wisdom',          topics: 'owls,wisdom,nocturnal' },
  { name: 'Hawks & Falcons',        topics: 'hawks,falcons,hunting' },
  { name: 'Swans & Lakes',          topics: 'swans,lakes,grace' },
  { name: 'Peacocks & Feathers',    topics: 'peacocks,feathers,display' },
  { name: 'Hummingbirds & Nectar',  topics: 'hummingbirds,nectar,hovering' },
  { name: 'Woodpeckers & Trees',    topics: 'woodpeckers,trees,drumming' },
  { name: 'Ants & Tunnels',         topics: 'ants,tunnels,colony' },
  { name: 'Beetles & Shells',       topics: 'beetles,shells,insects' },
  { name: 'Fireflies & Glowing',    topics: 'fireflies,glowing,summer' },
  { name: 'Ladybugs & Gardens',     topics: 'ladybugs,gardens,spots' },
  { name: 'Caterpillars & Cocoons', topics: 'caterpillars,cocoons,metamorphosis' },
  { name: 'Scorpions & Deserts',    topics: 'scorpions,deserts,venom' },
  { name: 'Chameleons & Colour',    topics: 'chameleons,colour,camouflage' },
  { name: 'Crocodiles & Swamps',    topics: 'crocodiles,swamps,predator' },
  { name: 'Hippos & Rivers',        topics: 'hippos,rivers,africa' },
  { name: 'Rhinos & Horns',         topics: 'rhinos,horns,endangered' },
  { name: 'Cheetahs & Speed',       topics: 'cheetahs,speed,hunting' },
  { name: 'Leopards & Spots',       topics: 'leopards,spots,stealth' },
  { name: 'Tigers & Stripes',       topics: 'tigers,stripes,jungle' },
  { name: 'Bears & Hibernation',    topics: 'bears,hibernation,forest' },
  { name: 'Moose & Tundra',         topics: 'moose,tundra,antlers' },
  { name: 'Bison & Plains',         topics: 'bison,plains,grazing' },
  { name: 'Otters & Streams',       topics: 'otters,streams,playful' },
  { name: 'Beavers & Dams',         topics: 'beavers,dams,rivers' },
  { name: 'Raccoons & Night',       topics: 'raccoons,night,foraging' },
  { name: 'Sloths & Canopy',        topics: 'sloths,canopy,slow' },
  { name: 'Monkeys & Vines',        topics: 'monkeys,vines,jungle' },
  { name: 'Parrots & Mimicry',      topics: 'parrots,mimicry,colourful' },
  { name: 'Toucans & Beaks',        topics: 'toucans,beaks,tropical' },
  { name: 'Pelicans & Fishing',     topics: 'pelicans,fishing,coast' },
  { name: 'Albatross & Oceans',     topics: 'albatross,oceans,wingspan' },
  { name: 'Puffins & Cliffs',       topics: 'puffins,cliffs,nesting' },
  { name: 'Storks & Nests',         topics: 'storks,nests,migration' },
  { name: 'Herons & Marshes',       topics: 'herons,marshes,wading' },
  { name: 'Kingfishers & Diving',   topics: 'kingfishers,diving,rivers' },
  { name: 'Cuckoos & Spring',       topics: 'cuckoos,spring,calling' },
  { name: 'Pigeons & Cities',       topics: 'pigeons,cities,flocking' },
  { name: 'Sparrows & Hedges',      topics: 'sparrows,hedges,chirping' },
  { name: 'Wrens & Bushes',         topics: 'wrens,bushes,tiny' },
  { name: 'Magpies & Shiny',        topics: 'magpies,shiny,collecting' },
  { name: 'Jays & Acorns',          topics: 'jays,acorns,woodland' },
  { name: 'Finches & Seeds',        topics: 'finches,seeds,singing' },
  { name: 'Canaries & Song',        topics: 'canaries,song,yellow' },
  { name: 'Doves & Peace',          topics: 'doves,peace,white' },
  { name: 'Vultures & Scavenging',  topics: 'vultures,scavenging,circling' },
  { name: 'Ostriches & Running',    topics: 'ostriches,running,flightless' },
  { name: 'Emus & Australia',       topics: 'emus,australia,flightless' },
  { name: 'Kiwis & New Zealand',    topics: 'kiwis,new zealand,nocturnal' },
  { name: 'Platypus & Oddities',    topics: 'platypus,oddities,australia' },
  { name: 'Armadillos & Armour',    topics: 'armadillos,armour,rolling' },
  { name: 'Porcupines & Quills',    topics: 'porcupines,quills,defence' },
  { name: 'Meerkats & Lookouts',    topics: 'meerkats,lookouts,desert' },
  { name: 'Lemurs & Madagascar',    topics: 'lemurs,madagascar,primates' },
  { name: 'Camels & Deserts',       topics: 'camels,deserts,humps' },
  { name: 'Llamas & Mountains',     topics: 'llamas,mountains,andes' },
  { name: 'Alpacas & Wool',         topics: 'alpacas,wool,soft' },
  { name: 'Goats & Climbing',       topics: 'goats,climbing,mountains' },
  { name: 'Sheep & Pastures',       topics: 'sheep,pastures,wool' },
  { name: 'Cows & Meadows',         topics: 'cows,meadows,grazing' },
  { name: 'Pigs & Farms',           topics: 'pigs,farms,mud' },
  { name: 'Chickens & Coops',       topics: 'chickens,coops,eggs' },
  { name: 'Ducks & Ponds',          topics: 'ducks,ponds,quacking' },
  { name: 'Turkeys & Gobbling',     topics: 'turkeys,gobbling,farmyard' },
  { name: 'Donkeys & Trails',       topics: 'donkeys,trails,stubborn' },
  { name: 'Rabbits & Burrows',      topics: 'rabbits,burrows,hopping' },
  { name: 'Hamsters & Wheels',      topics: 'hamsters,wheels,pets' },
  { name: 'Guinea Pigs & Squeaking',topics: 'guinea pigs,squeaking,pets' },
  { name: 'Goldfish & Bowls',       topics: 'goldfish,bowls,swimming' },
  { name: 'Parakeets & Cages',      topics: 'parakeets,cages,chirping' },
  { name: 'Tortoises & Shells',     topics: 'tortoises,shells,slow' },
  { name: 'Geckos & Walls',         topics: 'geckos,walls,climbing' },
  { name: 'Iguanas & Basking',      topics: 'iguanas,basking,reptiles' },
  { name: 'Axolotls & Regeneration',topics: 'axolotls,regeneration,aquatic' },
  { name: 'Salamanders & Damp',     topics: 'salamanders,damp,amphibians' },
  { name: 'Newts & Ponds',          topics: 'newts,ponds,amphibians' },
  // Extra themes 466-565
  { name: 'Astronomy & Nebulae',    topics: 'nebulae,astronomy,gas' },
  { name: 'Black Holes & Gravity',  topics: 'black holes,gravity,space' },
  { name: 'Satellites & Orbits',    topics: 'satellites,orbits,space' },
  { name: 'Rockets & Launches',     topics: 'rockets,launches,propulsion' },
  { name: 'Mars & Rovers',          topics: 'mars,rovers,exploration' },
  { name: 'Jupiter & Moons',        topics: 'jupiter,moons,gas giant' },
  { name: 'Saturn & Rings',         topics: 'saturn,rings,planet' },
  { name: 'Galaxies & Clusters',    topics: 'galaxies,clusters,universe' },
  { name: 'Telescopes & Lenses',    topics: 'telescopes,lenses,optics' },
  { name: 'Astronauts & Suits',     topics: 'astronauts,suits,spacewalk' },
  { name: 'Pottery & Glazing',      topics: 'pottery,glazing,kiln' },
  { name: 'Sculpture & Marble',     topics: 'sculpture,marble,carving' },
  { name: 'Mosaics & Tiles',        topics: 'mosaics,tiles,patterns' },
  { name: 'Stained Glass',          topics: 'stained glass,windows,light' },
  { name: 'Calligraphy & Ink',      topics: 'calligraphy,ink,writing' },
  { name: 'Printmaking & Press',    topics: 'printmaking,press,etching' },
  { name: 'Weaving & Looms',        topics: 'weaving,looms,fabric' },
  { name: 'Quilting & Patchwork',   topics: 'quilting,patchwork,sewing' },
  { name: 'Embroidery & Thread',    topics: 'embroidery,thread,needlework' },
  { name: 'Woodcarving & Chisels',  topics: 'woodcarving,chisels,craft' },
  { name: 'Blacksmithing & Forge',  topics: 'blacksmithing,forge,anvil' },
  { name: 'Glassblowing & Heat',    topics: 'glassblowing,heat,molten' },
  { name: 'Leatherwork & Hides',    topics: 'leatherwork,hides,tanning' },
  { name: 'Basketry & Reeds',       topics: 'basketry,reeds,weaving' },
  { name: 'Candle Making & Wax',    topics: 'candle making,wax,wicks' },
  { name: 'Soap Making & Lye',      topics: 'soap making,lye,fragrance' },
  { name: 'Brewing & Hops',         topics: 'brewing,hops,fermentation' },
  { name: 'Distilling & Spirits',   topics: 'distilling,spirits,alcohol' },
  { name: 'Cheese Aging & Caves',   topics: 'cheese aging,caves,rind' },
  { name: 'Bread & Sourdough',      topics: 'sourdough,starter,fermentation' },
  { name: 'Pasta & Italy',          topics: 'pasta,italy,flour' },
  { name: 'Sushi & Japan',          topics: 'sushi,japan,rice' },
  { name: 'Curry & Spices',         topics: 'curry,spices,india' },
  { name: 'Tacos & Mexico',         topics: 'tacos,mexico,salsa' },
  { name: 'Pizza & Ovens',          topics: 'pizza,ovens,dough' },
  { name: 'Dim Sum & Steaming',     topics: 'dim sum,steaming,dumplings' },
  { name: 'Ramen & Broth',          topics: 'ramen,broth,noodles' },
  { name: 'Barbecue & Smoke',       topics: 'barbecue,smoke,ribs' },
  { name: 'Waffles & Syrup',        topics: 'waffles,syrup,breakfast' },
  { name: 'Pancakes & Flipping',    topics: 'pancakes,flipping,batter' },
  { name: 'Coffee & Beans',         topics: 'coffee,beans,roasting' },
  { name: 'Tea & Leaves',           topics: 'tea,leaves,brewing' },
  { name: 'Smoothies & Blending',   topics: 'smoothies,blending,fruit' },
  { name: 'Cocktails & Mixing',     topics: 'cocktails,mixing,shaking' },
  { name: 'Vineyards & Grapes',     topics: 'vineyards,grapes,wine' },
  { name: 'Olive Oil & Pressing',   topics: 'olive oil,pressing,mediterranean' },
  { name: 'Honey & Beekeeping',     topics: 'honey,beekeeping,hives' },
  { name: 'Jam & Preserving',       topics: 'jam,preserving,fruit' },
  { name: 'Pickling & Vinegar',     topics: 'pickling,vinegar,preserving' },
  { name: 'Smoking & Curing',       topics: 'smoking,curing,meat' },
  { name: 'Castles & Moats',        topics: 'castles,moats,drawbridge' },
  { name: 'Cathedrals & Spires',    topics: 'cathedrals,spires,gothic' },
  { name: 'Pyramids & Pharaohs',    topics: 'pyramids,pharaohs,egypt' },
  { name: 'Colosseum & Gladiators', topics: 'colosseum,gladiators,rome' },
  { name: 'Great Wall & China',     topics: 'great wall,china,ancient' },
  { name: 'Temples & Shrines',      topics: 'temples,shrines,worship' },
  { name: 'Palaces & Royalty',      topics: 'palaces,royalty,throne' },
  { name: 'Lighthouses & Beacons',  topics: 'lighthouses,beacons,coast' },
  { name: 'Windmills & Grain',      topics: 'windmills,grain,milling' },
  { name: 'Aqueducts & Water',      topics: 'aqueducts,water,roman' },
  { name: 'Skyscrapers & Steel',    topics: 'skyscrapers,steel,height' },
  { name: 'Domes & Arches',         topics: 'domes,arches,architecture' },
  { name: 'Columns & Pillars',      topics: 'columns,pillars,classical' },
  { name: 'Gargoyles & Cathedrals', topics: 'gargoyles,cathedrals,stone' },
  { name: 'Drawbridges & Castles',  topics: 'drawbridges,castles,defence' },
  { name: 'Towers & Heights',       topics: 'towers,heights,views' },
  { name: 'Tunnels & Boring',       topics: 'tunnels,boring,underground' },
  { name: 'Canals & Locks',         topics: 'canals,locks,waterways' },
  { name: 'Harbours & Docks',       topics: 'harbours,docks,ships' },
  { name: 'Airports & Runways',     topics: 'airports,runways,flying' },
  { name: 'Railways & Stations',    topics: 'railways,stations,platforms' },
  { name: 'Submarines & Depth',     topics: 'submarines,depth,pressure' },
  { name: 'Helicopters & Rotors',   topics: 'helicopters,rotors,hovering' },
  { name: 'Balloons & Baskets',     topics: 'balloons,baskets,floating' },
  { name: 'Gliders & Thermals',     topics: 'gliders,thermals,soaring' },
  { name: 'Parachutes & Jumping',   topics: 'parachutes,jumping,freefall' },
  { name: 'Scooters & Streets',     topics: 'scooters,streets,riding' },
  { name: 'Motorcycles & Roads',    topics: 'motorcycles,roads,engines' },
  { name: 'Trucks & Hauling',       topics: 'trucks,hauling,freight' },
  { name: 'Tractors & Fields',      topics: 'tractors,fields,ploughing' },
  { name: 'Cranes & Construction',  topics: 'cranes,construction,lifting' },
  { name: 'Bulldozers & Digging',   topics: 'bulldozers,digging,earth' },
  { name: 'Excavators & Sites',     topics: 'excavators,sites,digging' },
  { name: 'Forklifts & Warehouses', topics: 'forklifts,warehouses,lifting' },
  { name: 'Conveyor Belts & Factories', topics: 'conveyor belts,factories,production' },
  { name: 'Gears & Mechanisms',     topics: 'gears,mechanisms,turning' },
  { name: 'Springs & Coils',        topics: 'springs,coils,tension' },
  { name: 'Pulleys & Ropes',        topics: 'pulleys,ropes,lifting' },
  { name: 'Levers & Fulcrums',      topics: 'levers,fulcrums,force' },
  { name: 'Magnets & Fields',       topics: 'magnets,fields,attraction' },
  { name: 'Batteries & Charge',     topics: 'batteries,charge,energy' },
  { name: 'Circuits & Wires',       topics: 'circuits,wires,electricity' },
  { name: 'Lasers & Light',         topics: 'lasers,light,beams' },
  { name: 'Mirrors & Reflection',   topics: 'mirrors,reflection,glass' },
  { name: 'Prisms & Rainbows',      topics: 'prisms,rainbows,refraction' },
  { name: 'Lenses & Focus',         topics: 'lenses,focus,optics' },
  { name: 'Microscopes & Cells',    topics: 'microscopes,cells,biology' },
  { name: 'DNA & Genetics',         topics: 'dna,genetics,heredity' },
  { name: 'Fossils & Layers',       topics: 'fossils,layers,sediment' },
  { name: 'Crystals & Growth',      topics: 'crystals,growth,minerals' },
  // Extra themes 566-665
  { name: 'Volcanoes & Magma',      topics: 'volcanoes,magma,mantle' },
  { name: 'Tectonic Plates',        topics: 'tectonic,plates,continental' },
  { name: 'Geysers & Steam',        topics: 'geysers,steam,thermal' },
  { name: 'Hot Springs & Minerals', topics: 'hot springs,minerals,thermal' },
  { name: 'Waterfalls & Mist',      topics: 'waterfalls,mist,cascading' },
  { name: 'Icebergs & Floating',    topics: 'icebergs,floating,arctic' },
  { name: 'Coral & Polyps',         topics: 'coral,polyps,reef' },
  { name: 'Kelp & Forests',         topics: 'kelp,forests,underwater' },
  { name: 'Mangroves & Roots',      topics: 'mangroves,roots,coastal' },
  { name: 'Wetlands & Marshes',     topics: 'wetlands,marshes,biodiversity' },
  { name: 'Savannas & Grasslands',  topics: 'savannas,grasslands,africa' },
  { name: 'Tundra & Permafrost',    topics: 'tundra,permafrost,arctic' },
  { name: 'Taiga & Conifers',       topics: 'taiga,conifers,boreal' },
  { name: 'Steppes & Nomads',       topics: 'steppes,nomads,grassland' },
  { name: 'Oases & Palms',          topics: 'oases,palms,water' },
  { name: 'Fjords & Cliffs',        topics: 'fjords,cliffs,norway' },
  { name: 'Atolls & Lagoons',       topics: 'atolls,lagoons,tropical' },
  { name: 'Deltas & Sediment',      topics: 'deltas,sediment,rivers' },
  { name: 'Canyons & Gorges',       topics: 'canyons,gorges,erosion' },
  { name: 'Plateaus & Mesas',       topics: 'plateaus,mesas,flat' },
  { name: 'Chess & Strategy',       topics: 'chess,strategy,checkmate' },
  { name: 'Cards & Decks',          topics: 'cards,decks,shuffling' },
  { name: 'Dice & Probability',     topics: 'dice,probability,rolling' },
  { name: 'Board Games & Tokens',   topics: 'board games,tokens,playing' },
  { name: 'Dominoes & Tiles',       topics: 'dominoes,tiles,matching' },
  { name: 'Darts & Bullseye',       topics: 'darts,bullseye,throwing' },
  { name: 'Billiards & Cues',       topics: 'billiards,cues,pockets' },
  { name: 'Bowling & Pins',         topics: 'bowling,pins,strikes' },
  { name: 'Tennis & Rackets',       topics: 'tennis,rackets,court' },
  { name: 'Golf & Greens',          topics: 'golf,greens,putting' },
  { name: 'Cricket & Wickets',      topics: 'cricket,wickets,batting' },
  { name: 'Rugby & Scrums',         topics: 'rugby,scrums,tackling' },
  { name: 'Boxing & Gloves',        topics: 'boxing,gloves,ring' },
  { name: 'Wrestling & Mats',       topics: 'wrestling,mats,grappling' },
  { name: 'Fencing & Swords',       topics: 'fencing,swords,parry' },
  { name: 'Gymnastics & Balance',   topics: 'gymnastics,balance,tumbling' },
  { name: 'Diving & Platforms',     topics: 'diving,platforms,splash' },
  { name: 'Rowing & Oars',          topics: 'rowing,oars,sculling' },
  { name: 'Sailing & Wind',         topics: 'sailing,wind,tacking' },
  { name: 'Skiing & Powder',        topics: 'skiing,powder,slopes' },
  { name: 'Curling & Ice',          topics: 'curling,ice,stones' },
  { name: 'Hockey & Pucks',         topics: 'hockey,pucks,rink' },
  { name: 'Basketball & Hoops',     topics: 'basketball,hoops,dribbling' },
  { name: 'Baseball & Diamonds',    topics: 'baseball,diamonds,pitching' },
  { name: 'Football & Touchdowns',  topics: 'football,touchdowns,gridiron' },
  { name: 'Soccer & Goals',         topics: 'soccer,goals,passing' },
  { name: 'Badminton & Shuttlecocks', topics: 'badminton,shuttlecocks,net' },
  { name: 'Table Tennis & Paddles', topics: 'table tennis,paddles,spin' },
  { name: 'Squash & Courts',        topics: 'squash,courts,racket' },
  { name: 'Climbing & Ropes',       topics: 'climbing,ropes,bouldering' },
  { name: 'Piano & Keys',           topics: 'piano,keys,melody' },
  { name: 'Guitar & Strings',       topics: 'guitar,strings,chords' },
  { name: 'Drums & Rhythm',         topics: 'drums,rhythm,percussion' },
  { name: 'Violin & Bowing',        topics: 'violin,bowing,strings' },
  { name: 'Flute & Woodwind',       topics: 'flute,woodwind,breath' },
  { name: 'Trumpet & Brass',        topics: 'trumpet,brass,fanfare' },
  { name: 'Saxophone & Jazz',       topics: 'saxophone,jazz,improvisation' },
  { name: 'Harp & Plucking',        topics: 'harp,plucking,strings' },
  { name: 'Cello & Orchestra',      topics: 'cello,orchestra,deep' },
  { name: 'Bagpipes & Scotland',    topics: 'bagpipes,scotland,highland' },
  { name: 'Opera & Arias',          topics: 'opera,arias,singing' },
  { name: 'Ballet & Pointe',        topics: 'ballet,pointe,grace' },
  { name: 'Tap Dance & Rhythm',     topics: 'tap dance,rhythm,shoes' },
  { name: 'Salsa & Latin',          topics: 'salsa,latin,dancing' },
  { name: 'Waltz & Ballroom',       topics: 'waltz,ballroom,elegance' },
  { name: 'Breakdancing & Spins',   topics: 'breakdancing,spins,street' },
  { name: 'Puppets & Strings',      topics: 'puppets,strings,theatre' },
  { name: 'Circus & Acrobats',      topics: 'circus,acrobats,trapeze' },
  { name: 'Magic & Illusions',      topics: 'magic,illusions,tricks' },
  { name: 'Juggling & Balls',       topics: 'juggling,balls,coordination' },
  { name: 'Clowns & Comedy',        topics: 'clowns,comedy,laughter' },
  { name: 'Masks & Theatre',        topics: 'masks,theatre,performance' },
  { name: 'Mime & Silence',         topics: 'mime,silence,expression' },
  { name: 'Poetry & Verse',         topics: 'poetry,verse,rhyme' },
  { name: 'Novels & Fiction',       topics: 'novels,fiction,storytelling' },
  { name: 'Comics & Panels',        topics: 'comics,panels,illustration' },
  { name: 'Newspapers & Headlines', topics: 'newspapers,headlines,journalism' },
  { name: 'Maps & Cartography',     topics: 'maps,cartography,navigation' },
  { name: 'Compasses & North',      topics: 'compasses,north,direction' },
  { name: 'Sundials & Shadows',     topics: 'sundials,shadows,time' },
  { name: 'Hourglasses & Sand',     topics: 'hourglasses,sand,time' },
  { name: 'Pendulums & Swinging',   topics: 'pendulums,swinging,gravity' },
  { name: 'Thermometers & Heat',    topics: 'thermometers,heat,temperature' },
  { name: 'Barometers & Pressure',  topics: 'barometers,pressure,weather' },
  { name: 'Windvanes & Direction',  topics: 'windvanes,direction,weather' },
  { name: 'Sundials & Time',        topics: 'sundials,time,ancient' },
  { name: 'Abacus & Counting',      topics: 'abacus,counting,mathematics' },
  { name: 'Typewriters & Keys',     topics: 'typewriters,keys,writing' },
  { name: 'Telegraphs & Morse',     topics: 'telegraphs,morse,communication' },
  { name: 'Radios & Waves',         topics: 'radios,waves,broadcasting' },
  { name: 'Vinyl & Records',        topics: 'vinyl,records,turntable' },
  { name: 'Cameras & Film',         topics: 'cameras,film,photography' },
  { name: 'Projectors & Cinema',    topics: 'projectors,cinema,reels' },
  { name: 'Lightbulbs & Edison',    topics: 'lightbulbs,edison,invention' },
  { name: 'Steam Engines & Pistons',topics: 'steam engines,pistons,industrial' },
  { name: 'Clockwork & Gears',      topics: 'clockwork,gears,mechanical' },
  { name: 'Printing & Gutenberg',   topics: 'printing,gutenberg,press' },
  { name: 'Spinning Wheels & Yarn', topics: 'spinning wheels,yarn,fibre' },
  { name: 'Looms & Fabric',         topics: 'looms,fabric,weaving' },
  { name: 'Anvils & Hammering',     topics: 'anvils,hammering,metal' },
  { name: 'Bellows & Forging',      topics: 'bellows,forging,fire' },
];
