// Word → clue mapping for crossword generation
// Words are 3-5 letters, general knowledge clues
export const clueBank = {
  // 3-letter words
  "ace":"Top card","act":"Stage performance","add":"Sum up","age":"How old","aid":"Help out","aim":"Target","air":"We breathe it",
  "ale":"Pub drink","ant":"Tiny insect","ape":"Primate","arc":"Curved line","ark":"Noah's vessel","arm":"Body limb","art":"Gallery display",
  "ash":"Fire remains","ate":"Had a meal","awe":"Wonder","axe":"Chopping tool","bad":"Not good","bag":"Carry items in",
  "ban":"Prohibit","bar":"Pub counter","bat":"Flying mammal","bay":"Coastal inlet","bed":"Sleep on it","bee":"Honey maker",
  "bet":"Wager","big":"Large","bin":"Trash holder","bit":"Small piece","bow":"Ribbon shape","box":"Cardboard container",
  "boy":"Young male","bud":"Flower start","bug":"Small insect","bun":"Bread roll","bus":"Public transport","but":"However",
  "buy":"Purchase","cab":"Taxi","cam":"Camera part","can":"Tin container","cap":"Head cover","car":"Road vehicle",
  "cat":"Feline pet","cob":"Corn center","cod":"Ocean fish","cot":"Baby bed","cow":"Farm animal","cry":"Shed tears",
  "cub":"Young bear","cup":"Drink from it","cut":"Use scissors","dam":"River barrier","day":"24 hours","den":"Animal home",
  "dew":"Morning drops","did":"Past action","dig":"Use a shovel","dim":"Not bright","dip":"Quick swim","dog":"Loyal pet",
  "dot":"Small point","dry":"Not wet","dub":"Give a name","dug":"Made a hole","dye":"Color fabric","ear":"Hearing organ",
  "eat":"Consume food","eel":"Snake fish","egg":"Breakfast item","elk":"Large deer","elm":"Shade tree","end":"Finish",
  "era":"Time period","eve":"Night before","ewe":"Female sheep","eye":"Sight organ","fan":"Cool breeze","far":"Not near",
  "fat":"Not thin","fax":"Send a page","fed":"Gave food","fee":"Payment due","few":"Not many","fig":"Sweet fruit",
  "fin":"Fish part","fir":"Pine tree","fit":"In shape","fix":"Repair","fly":"Take flight","fog":"Thick mist",
  "for":"In favor of","fox":"Sly animal","fry":"Cook in oil","fun":"Good times","fur":"Animal coat","gag":"Joke",
  "gap":"Opening","gas":"Fuel type","gem":"Precious stone","get":"Obtain","gin":"Clear spirit","got":"Received",
  "gum":"Chew on it","gun":"Weapon","gut":"Stomach","guy":"Fellow","gym":"Workout place","had":"Possessed",
  "ham":"Pork meat","has":"Possesses","hat":"Head wear","hay":"Dried grass","hen":"Female chicken","her":"Belonging to she",
  "hid":"Concealed","him":"Male pronoun","hip":"Body joint","hit":"Strike","hog":"Greedy pig","hop":"Small jump",
  "hot":"High temp","how":"In what way","hub":"Center point","hue":"Color shade","hug":"Embrace","hum":"Sing softly",
  "hut":"Small shelter","ice":"Frozen water","ill":"Not well","imp":"Little devil","ink":"Pen fluid","inn":"Small hotel",
  "ion":"Charged atom","ire":"Anger","irk":"Annoy","ivy":"Climbing plant","jab":"Quick punch","jag":"Sharp point",
  "jam":"Fruit spread","jar":"Glass container","jaw":"Mouth bone","jay":"Blue bird","jet":"Fast plane","jig":"Lively dance",
  "job":"Employment","jog":"Slow run","joy":"Happiness","jug":"Water pitcher","jut":"Stick out",
  "keg":"Beer barrel","key":"Lock opener","kid":"Young child","kin":"Family","kit":"Tool set",
  "lab":"Science room","lad":"Young boy","lag":"Fall behind","lap":"Once around","law":"Legal rule","lay":"Put down",
  "lea":"Meadow","led":"Guided","leg":"Walking limb","let":"Allow","lid":"Cover top","lip":"Mouth edge",
  "lit":"Set ablaze","log":"Wood piece","lot":"Great deal","low":"Not high","lug":"Carry heavy",
  "mad":"Angry","man":"Adult male","map":"Shows routes","mat":"Floor cover","max":"Most possible","may":"Perhaps",
  "men":"Plural of man","met":"Encountered","mid":"Middle","mix":"Blend","mob":"Angry crowd","mop":"Clean floors",
  "mud":"Wet earth","mug":"Coffee cup","nab":"Catch","nag":"Pester","nap":"Short sleep","net":"Catch fish",
  "new":"Not old","nil":"Zero","nip":"Small bite","nod":"Head gesture","nor":"Neither","not":"Negative","now":"At present",
  "nun":"Religious woman","nut":"Hard shell seed","oak":"Strong tree","oar":"Row a boat","oat":"Cereal grain",
  "odd":"Strange","ode":"Lyric poem","oil":"Cooking liquid","old":"Not young","one":"Single","opt":"Choose",
  "orb":"Sphere","ore":"Metal rock","our":"Belonging to us","out":"Not in","owe":"In debt","owl":"Night bird",
  "own":"Possess","pad":"Writing tablet","pal":"Friend","pan":"Cook in it","paw":"Animal foot","pay":"Give money",
  "pea":"Green veggie","peg":"Hang on it","pen":"Writing tool","pet":"Tame animal","pie":"Baked dish","pig":"Farm animal",
  "pin":"Sharp point","pit":"Deep hole","pod":"Pea holder","pop":"Burst","pot":"Cook in it","pry":"Snoop",
  "pub":"Bar","pug":"Small dog","pun":"Word joke","pup":"Young dog","put":"Place","rag":"Old cloth",
  "ram":"Male sheep","ran":"Moved fast","rap":"Knock","rat":"Rodent","raw":"Uncooked","ray":"Light beam",
  "red":"Color of roses","ref":"Game official","rib":"Chest bone","rid":"Free from","rig":"Setup","rim":"Edge",
  "rip":"Tear apart","rob":"Steal from","rod":"Fishing pole","rot":"Decay","row":"Line up","rub":"Massage",
  "rug":"Floor cover","run":"Move fast","rut":"Deep groove","rye":"Bread grain","sac":"Body pouch","sad":"Unhappy",
  "sag":"Droop","sap":"Tree fluid","sat":"Was seated","saw":"Cutting tool","say":"Speak","sea":"Ocean",
  "set":"Group","sew":"Stitch","shy":"Timid","sin":"Wrongdoing","sip":"Drink slowly","sir":"Polite title",
  "sit":"Take a seat","six":"Half dozen","ski":"Snow sport","sky":"Above us","sly":"Crafty","sob":"Cry hard",
  "sod":"Grass patch","son":"Male child","sop":"Soak up","sow":"Plant seeds","soy":"Bean sauce","spa":"Relaxation spot",
  "spy":"Secret agent","sty":"Pig pen","sub":"Sandwich","sue":"Take to court","sum":"Total","sun":"Daytime star",
  "tab":"Bill","tag":"Label","tan":"Sun color","tap":"Light knock","tar":"Road surface","tax":"Government levy",
  "tea":"Hot drink","ten":"Decade","the":"Common article","tie":"Neck wear","tin":"Metal can","tip":"Helpful hint",
  "toe":"Foot digit","ton":"Heavy weight","too":"Also","top":"Highest point","tow":"Pull along","toy":"Plaything",
  "try":"Attempt","tub":"Bath vessel","tug":"Pull hard","two":"A pair",
  "urn":"Vase","use":"Employ","van":"Delivery truck","vat":"Large tank","vet":"Animal doctor","via":"By way of",
  "vie":"Compete","vow":"Promise","wad":"Thick bundle","wag":"Tail motion","war":"Armed conflict","was":"Past tense of be",
  "wax":"Candle material","way":"Path","web":"Spider's work","wed":"Marry","wet":"Not dry","who":"Which person",
  "wig":"Fake hair","win":"Victory","wit":"Humor","woe":"Sorrow","wok":"Asian pan","won":"Was victorious",
  "woo":"Court","wow":"Amazement","yak":"Tibetan ox","yam":"Sweet potato","yap":"Small bark","yaw":"Veer off course",
  "yep":"Informal yes","yes":"Affirmative","yet":"Still","yew":"Evergreen tree","yin":"Dark force",
  "zap":"Destroy","zen":"Inner peace","zip":"Close fast","zoo":"Animal park",
  // 4-letter words
  "able":"Capable","acid":"Sour substance","aged":"Old","ally":"Partner","arch":"Curved structure","area":"Region",
  "army":"Military force","atom":"Tiny particle","auto":"Car","avid":"Eager","axle":"Wheel rod",
  "babe":"Infant","back":"Rear side","bait":"Fishing lure","bake":"Oven cook","bald":"No hair","ball":"Round toy",
  "band":"Music group","bank":"Money keeper","bare":"Uncovered","bark":"Dog sound","barn":"Farm building","base":"Bottom part",
  "bath":"Wash in it","bead":"Necklace piece","beam":"Light ray","bean":"Pod veggie","bear":"Forest animal","beat":"Rhythm",
  "beef":"Cow meat","beer":"Pub drink","bell":"Rings","belt":"Waist band","bend":"Curve","bike":"Two wheels",
  "bill":"Payment due","bind":"Tie up","bird":"Feathered flyer","bite":"Chomp","blow":"Wind gust","blue":"Sky color",
  "blur":"Not clear","boar":"Wild pig","boat":"Water vessel","body":"Physical form","bold":"Brave","bolt":"Door lock",
  "bomb":"Explosive","bond":"Connection","bone":"Skeleton part","book":"Read it","boot":"Foot cover","bore":"Dull person",
  "born":"Came to life","boss":"In charge","both":"Two together","bowl":"Soup dish","brim":"Hat edge","bulb":"Light source",
  "bulk":"Large amount","bull":"Male cow","bump":"Small collision","burn":"Fire damage","bush":"Small shrub","busy":"Not idle",
  "buzz":"Bee sound","cafe":"Coffee shop","cage":"Animal enclosure","cake":"Birthday treat","calf":"Young cow","calm":"Peaceful",
  "came":"Arrived","camp":"Outdoor stay","cape":"Superhero wear","card":"Birthday greeting","care":"Concern","cart":"Shopping wheels",
  "case":"Container","cash":"Paper money","cast":"Throw","cave":"Rock hollow","chef":"Kitchen boss","chin":"Face bottom",
  "chip":"Snack","chop":"Cut up","city":"Urban area","clam":"Shell creature","clap":"Hand sound","claw":"Sharp nail",
  "clay":"Pottery material","clip":"Fasten","clue":"Hint","coal":"Black fuel","coat":"Outer wear","coin":"Metal money",
  "cold":"Low temp","colt":"Young horse","comb":"Hair tool","cone":"Ice cream holder","cook":"Make food","cool":"Slightly cold",
  "cope":"Deal with","copy":"Duplicate","cord":"Thick string","core":"Center","cork":"Bottle stopper","corn":"Yellow veggie",
  "cost":"Price","cozy":"Warm and snug","crab":"Beach creature","crew":"Ship workers","crop":"Farm harvest","crow":"Black bird",
  "cube":"Six sided shape","cure":"Remedy","curl":"Hair shape","cute":"Adorable",
  "dale":"Valley","dame":"Lady","damp":"Slightly wet","dare":"Challenge","dark":"No light","dart":"Throwing game",
  "dash":"Run quickly","dawn":"Sunrise","deaf":"Cannot hear","deal":"Agreement","dear":"Beloved","deck":"Ship floor",
  "deed":"Action","deep":"Not shallow","deer":"Forest animal","deli":"Sandwich shop","dent":"Small damage","desk":"Work surface",
  "dial":"Phone part","dice":"Game cubes","diet":"Food plan","dime":"Ten cents","dine":"Eat out","dire":"Desperate",
  "dirt":"Soil","dish":"Plate","dock":"Boat parking","dome":"Round roof","done":"Finished","door":"Room entry",
  "dose":"Medicine amount","dove":"Peace bird","down":"Below","drag":"Pull along","draw":"Sketch","drip":"Water drop",
  "drop":"Let fall","drum":"Beat it","duck":"Pond bird","duel":"Two person fight","duke":"Noble title","dull":"Not sharp",
  "dune":"Sand hill","dusk":"Evening time","dust":"Fine particles","duty":"Obligation",
  "each":"Every one","earl":"Noble rank","earn":"Make money","ease":"Comfort","east":"Sunrise direction","easy":"Not hard",
  "echo":"Sound bounce","edge":"Border","edit":"Revise","else":"Otherwise","emit":"Give off","epic":"Grand tale",
  "even":"Level","ever":"At any time","evil":"Wicked","exam":"School test","exit":"Way out",
  "face":"Front of head","fact":"Truth","fade":"Lose color","fail":"Not succeed","fair":"Just","fake":"Not real",
  "fall":"Autumn","fame":"Celebrity","fang":"Sharp tooth","fare":"Ticket price","farm":"Grow crops","fast":"Quick",
  "fate":"Destiny","fawn":"Young deer","fear":"Be afraid","feat":"Achievement","feed":"Give food","feel":"Touch",
  "fell":"Chopped down","felt":"Touched","fern":"Forest plant","file":"Document","fill":"Make full","film":"Movie",
  "find":"Discover","fine":"Okay","fire":"Flames","firm":"Company","fish":"Swim creature","five":"Hand digits",
  "flag":"Country symbol","flat":"Level surface","flaw":"Defect","flea":"Tiny pest","fled":"Ran away","flew":"Took flight",
  "flip":"Turn over","flock":"Bird group","flow":"Move smoothly","foam":"Bubble mass","foal":"Baby horse","fold":"Bend over",
  "folk":"People","fond":"Affectionate","food":"Eat it","fool":"Silly person","foot":"Walk on it","ford":"River crossing",
  "fork":"Eating utensil","form":"Shape","fort":"Military base","foul":"Against rules","four":"After three","fowl":"Poultry",
  "free":"No cost","frog":"Pond jumper","from":"Starting point","fuel":"Powers engines","full":"Not empty","fume":"Toxic gas",
  "fund":"Money pool","fuse":"Safety device","fury":"Intense anger",
  "gale":"Strong wind","game":"Play it","gang":"Group","gate":"Fence opening","gave":"Donated","gaze":"Stare",
  "gear":"Equipment","gift":"Present","gild":"Cover in gold","girl":"Young female","give":"Hand over","glad":"Happy",
  "glow":"Soft light","glue":"Sticky stuff","goat":"Mountain animal","gold":"Precious metal","golf":"Club sport",
  "gone":"Left","good":"Not bad","grab":"Seize","gray":"Between black and white","grew":"Got bigger","grid":"Crossed lines",
  "grim":"Stern","grin":"Big smile","grip":"Hold tight","grit":"Determination","grow":"Get bigger","gulf":"Large bay",
  "gust":"Wind burst","guts":"Courage",
  "hail":"Ice rain","hair":"Head covering","half":"Fifty percent","hall":"Corridor","halt":"Stop","hand":"Five fingers",
  "hang":"Suspend","hard":"Not soft","hare":"Fast rabbit","harm":"Damage","harp":"String instrument","hate":"Despise",
  "haul":"Carry heavy","have":"Possess","hawk":"Bird of prey","haze":"Light fog","head":"Body top","heal":"Get better",
  "heap":"Pile","hear":"Use ears","heat":"Warmth","heed":"Pay attention","heel":"Foot back","held":"Gripped",
  "help":"Assist","herb":"Cooking plant","herd":"Animal group","here":"This place","hero":"Brave person","hide":"Conceal",
  "high":"Tall","hike":"Long walk","hill":"Small mountain","hint":"Subtle clue","hire":"Employ","hive":"Bee home",
  "hold":"Grip","hole":"Opening","home":"Where you live","hood":"Head cover","hook":"Curved metal","hope":"Wish for",
  "horn":"Animal feature","hose":"Water tube","host":"Party giver","hour":"Sixty minutes","howl":"Wolf cry","huge":"Very big",
  "hull":"Ship body","hump":"Camel feature","hung":"Suspended","hunt":"Search for prey","hurt":"Feel pain","husk":"Corn cover",
  // 5-letter words
  "about":"Approximately","above":"Higher than","abuse":"Mistreat","actor":"Movie star","admit":"Confess","adult":"Grown up",
  "after":"Following","again":"Once more","agent":"Representative","agree":"Same opinion","alarm":"Wake up call","album":"Photo collection",
  "alert":"Warning","alien":"From space","align":"Line up","alive":"Not dead","allow":"Permit","alone":"By yourself",
  "along":"Beside","angel":"Heavenly being","anger":"Fury","angle":"Corner degree","angry":"Mad","ankle":"Foot joint",
  "apple":"Red fruit","arena":"Sports venue","argue":"Disagree","arise":"Get up","armor":"Knight wear","avoid":"Stay away",
  "award":"Prize","awful":"Terrible","bacon":"Breakfast meat","badge":"ID pin","basic":"Simple","beach":"Sandy shore",
  "being":"Existing","below":"Under","bench":"Park seat","berry":"Small fruit","birth":"Being born","black":"Darkest color",
  "blade":"Knife edge","blame":"Hold responsible","blank":"Empty","blast":"Explosion","blaze":"Big fire","bleed":"Lose blood",
  "blend":"Mix together","bless":"Give thanks","blind":"Cannot see","block":"Solid piece","blood":"Red fluid","bloom":"Flower opens",
  "blown":"Wind moved","board":"Flat wood","bonus":"Extra reward","brain":"Think organ","brand":"Product name","brave":"Courageous",
  "bread":"Sandwich base","break":"Snap apart","brick":"Wall block","bride":"Wedding woman","brief":"Short","bring":"Carry here",
  "broad":"Wide","brown":"Earth color","brush":"Paint tool","build":"Construct","bunch":"Group","burst":"Pop open",
  "cabin":"Log house","cable":"Thick wire","candy":"Sweet treat","carry":"Transport","catch":"Grab","cause":"Reason",
  "chain":"Metal links","chair":"Sit on it","charm":"Attractiveness","chase":"Run after","cheap":"Low cost","check":"Verify",
  "cheek":"Face side","cheer":"Shout joy","chess":"Board game","chest":"Treasure box","chief":"Leader","child":"Young person",
  "chill":"Cool down","china":"Tea set material","chunk":"Large piece","claim":"Assert","class":"School group","clean":"Not dirty",
  "clear":"Transparent","clerk":"Store worker","cliff":"Steep rock","climb":"Go up","clock":"Tells time","close":"Shut",
  "cloth":"Fabric","cloud":"Sky puff","coach":"Sports trainer","coast":"Shoreline","color":"Red or blue","coral":"Reef builder",
  "couch":"Living room seat","count":"Number up","court":"Tennis area","cover":"Put over","crack":"Break line","craft":"Handmade art",
  "crane":"Tall bird","crash":"Collision","crazy":"Wild","cream":"Coffee addition","creek":"Small stream","crime":"Illegal act",
  "cross":"Go across","crowd":"Many people","crown":"Royal headwear","crush":"Squeeze hard","curve":"Bend","cycle":"Repeat",
  "daily":"Every day","dance":"Move to music","death":"End of life","delay":"Postpone","dense":"Thick","depth":"How deep",
  "devil":"Evil being","diary":"Daily journal","dirty":"Not clean","doubt":"Uncertainty","draft":"First version","drain":"Empty out",
  "drama":"Theater art","dream":"Sleep vision","dress":"Clothing","dried":"Not wet","drift":"Float along","drill":"Make holes",
  "drink":"Beverage","drive":"Steer a car","drown":"Sink in water","dying":"Near death",
  "eager":"Enthusiastic","early":"Before time","earth":"Our planet","eight":"After seven","elbow":"Arm joint","elder":"Older person",
  "elect":"Vote for","elite":"Top tier","empty":"Nothing inside","enemy":"Foe","enjoy":"Take pleasure","enter":"Go in",
  "equal":"Same amount","error":"Mistake","event":"Happening","every":"Each one","exact":"Precise","extra":"Additional",
  "faint":"Nearly pass out","faith":"Belief","false":"Not true","feast":"Big meal","fence":"Yard border","fever":"High temp",
  "fiber":"Thread","field":"Open land","fifty":"Half hundred","fight":"Battle","final":"Last one","flame":"Fire tongue",
  "flash":"Quick light","fleet":"Ship group","flesh":"Body tissue","float":"Stay on water","flood":"Too much water","floor":"Walk on it",
  "flour":"Baking powder","fluid":"Liquid","focus":"Concentrate","force":"Power","forge":"Shape metal","forth":"Forward",
  "found":"Discovered","frame":"Picture border","fresh":"Newly made","front":"Opposite of back","frost":"Ice crystals","fruit":"Apple or banana",
  "funny":"Makes you laugh","ghost":"Spooky spirit","giant":"Very large","given":"Handed over","glass":"See through","globe":"World model",
  "glove":"Hand cover","going":"In motion","grace":"Elegance","grade":"School mark","grain":"Wheat or rice","grand":"Magnificent",
  "grant":"Give funds","grape":"Wine fruit","grasp":"Understand","grass":"Lawn cover","grave":"Burial site","great":"Wonderful",
  "green":"Grass color","greet":"Say hello","grief":"Deep sorrow","grill":"BBQ cook","grind":"Crush fine","gross":"Disgusting",
  "group":"Collection","grove":"Small forest","grown":"Matured","guard":"Protect","guess":"Estimate","guest":"Visitor",
  "guide":"Show the way","guilt":"Feeling wrong","habit":"Regular practice","happy":"Joyful","harsh":"Severe","heart":"Love organ",
  "heavy":"Weighs a lot","hence":"Therefore","hobby":"Leisure activity","honey":"Bee product","honor":"Respect","horse":"Riding animal",
  "hotel":"Stay overnight","house":"Home","human":"Person","humor":"Comedy","hurry":"Rush","ideal":"Perfect",
  "image":"Picture","imply":"Suggest","inner":"Inside","irony":"Opposite meaning","issue":"Problem","ivory":"Elephant tusk",
  "jewel":"Gemstone","joint":"Connection point","joker":"Funny person","judge":"Court official","juice":"Fruit drink",
  "knife":"Cutting tool","knock":"Door sound","known":"Recognized","label":"Name tag","labor":"Hard work","large":"Big",
  "laser":"Light beam","later":"After now","laugh":"Ha ha","layer":"One thickness","learn":"Gain knowledge","lease":"Rental agreement",
  "least":"Minimum","leave":"Go away","legal":"Lawful","lemon":"Sour fruit","level":"Flat","light":"Not dark",
  "limit":"Maximum","linen":"Bed fabric","liver":"Body organ","local":"Nearby","lodge":"Mountain cabin","logic":"Reasoning",
  "loose":"Not tight","lover":"Romantic partner","lower":"Bring down","loyal":"Faithful","lucky":"Fortunate","lunch":"Midday meal",
  "magic":"Illusion art","major":"Important","manor":"Large estate","maple":"Syrup tree","march":"Walk in step","match":"Same pair",
  "mayor":"City leader","media":"News outlets","mercy":"Compassion","merit":"Deserve","metal":"Iron or steel","might":"Perhaps",
  "minor":"Small","model":"Miniature copy","money":"Currency","month":"Year division","moral":"Ethical lesson","motor":"Engine",
  "mount":"Climb up","mouse":"Small rodent","mouth":"Speak from it","movie":"Film","music":"Melody","naive":"Innocent",
  "nerve":"Body signal wire","never":"Not ever","night":"After sunset","noble":"Honorable","noise":"Loud sound","north":"Compass top",
  "noted":"Famous","novel":"Fiction book","nurse":"Medical helper","occur":"Happen","ocean":"Vast sea","offer":"Propose",
  "often":"Frequently","olive":"Green fruit","onset":"Beginning","opera":"Singing drama","orbit":"Circle path","order":"Arrange",
  "organ":"Body part","other":"Different","outer":"External","owner":"Possessor","paint":"Color walls","panel":"Flat board",
  "panic":"Sudden fear","paper":"Write on it","party":"Celebration","pasta":"Italian food","patch":"Repair piece","pause":"Brief stop",
  "peace":"No war","peach":"Fuzzy fruit","pearl":"Oyster gem","penny":"One cent","phase":"Stage","phone":"Call device",
  "photo":"Picture","piano":"Key instrument","piece":"Part","pilot":"Flies planes","pitch":"Throw","pizza":"Italian pie",
  "place":"Location","plain":"Simple","plane":"Flying machine","plant":"Green life","plate":"Dinner dish","plaza":"Town square",
  "plead":"Beg","plumb":"Straight down","point":"Sharp end","polar":"Arctic region","pound":"British money","power":"Strength",
  "press":"Push down","price":"Cost","pride":"Self respect","prime":"First rate","print":"Put on paper","prior":"Before",
  "prize":"Award","proof":"Evidence","proud":"Self satisfied","prove":"Show truth","pulse":"Heart beat","punch":"Fist hit",
  "pupil":"Student","queen":"Royal woman","quest":"Search","queue":"Waiting line","quick":"Fast","quiet":"Not loud",
  "quite":"Rather","quote":"Repeat words","radar":"Detection system","radio":"Listen to it","raise":"Lift up","rally":"Gathering",
  "ranch":"Cattle farm","range":"Extent","rapid":"Very fast","ratio":"Proportion","reach":"Extend to","react":"Respond",
  "ready":"Prepared","realm":"Kingdom","rebel":"Resist authority","reign":"Rule","relax":"Unwind","reply":"Answer back",
  "rider":"On horseback","ridge":"Mountain top","rifle":"Long gun","right":"Correct","rigid":"Stiff","risky":"Dangerous",
  "rival":"Competitor","river":"Flowing water","robin":"Red breast bird","robot":"Machine worker","rocky":"Full of stones",
  "rough":"Not smooth","round":"Circular","route":"Travel path","royal":"Of a king","ruler":"Measuring stick","rural":"Countryside",
  "sadly":"Unfortunately","saint":"Holy person","salad":"Veggie mix","sauce":"Food topping","scale":"Weigh on it","scare":"Frighten",
  "scene":"Movie part","scope":"Range","score":"Game points","scout":"Explorer","sense":"Feeling","serve":"Wait on",
  "seven":"Lucky number","shade":"Shadow","shake":"Tremble","shame":"Disgrace","shape":"Form","share":"Divide up",
  "shark":"Ocean predator","sharp":"Pointy","sheep":"Wool animal","sheet":"Bed cover","shelf":"Storage ledge","shell":"Beach find",
  "shift":"Move over","shine":"Give light","shirt":"Upper wear","shock":"Surprise","shore":"Beach","short":"Not tall",
  "shout":"Yell","sight":"Vision","silly":"Foolish","since":"From then","sixth":"After fifth","sixty":"Six tens",
  "skill":"Ability","skull":"Head bone","slave":"Forced worker","sleep":"Night rest","slice":"Cut piece","slide":"Playground fun",
  "slope":"Incline","small":"Little","smart":"Intelligent","smell":"Use nose","smile":"Happy face","smoke":"Fire output",
  "snake":"Slithering reptile","solar":"Sun powered","solid":"Not liquid","solve":"Find answer","sorry":"Apologetic",
  "sound":"Noise","south":"Compass bottom","space":"Outer void","spare":"Extra","spark":"Fire start","speak":"Talk",
  "speed":"How fast","spend":"Use money","spice":"Food flavor","spine":"Backbone","split":"Divide","spoon":"Soup utensil",
  "sport":"Athletic game","spray":"Mist","squad":"Small team","stack":"Pile up","staff":"Employees","stage":"Theater platform",
  "stain":"Dirty mark","stair":"Step up","stake":"Pointed stick","stale":"Not fresh","stamp":"Mail mark","stand":"Be upright",
  "stare":"Look hard","start":"Begin","state":"Condition","steak":"Beef cut","steal":"Take illegally","steam":"Hot vapor",
  "steel":"Strong metal","steep":"Very angled","steer":"Guide","stern":"Ship back","stick":"Branch","stiff":"Not flexible",
  "still":"Not moving","stock":"Store supply","stone":"Small rock","stood":"Was standing","store":"Shop","storm":"Bad weather",
  "story":"Tale","stove":"Cook on it","strip":"Narrow piece","stuck":"Cannot move","study":"Learn","stuff":"Things",
  "style":"Fashion","sugar":"Sweet crystal","suite":"Hotel room","sunny":"Bright day","super":"Great","surge":"Sudden increase",
  "swamp":"Wetland","swear":"Promise","sweep":"Clean floor","sweet":"Sugary taste","swept":"Cleaned","swift":"Very fast",
  "swing":"Playground ride","sword":"Knight weapon","syrup":"Pancake topping",
  "table":"Eat at it","taste":"Flavor","teach":"Instruct","teeth":"Mouth bones","thank":"Show gratitude","theme":"Main idea",
  "thick":"Not thin","thing":"Object","think":"Use brain","third":"After second","thorn":"Rose prickle","those":"Them",
  "three":"After two","threw":"Tossed","throw":"Toss","thumb":"Short finger","tiger":"Striped cat","tight":"Not loose",
  "timer":"Counts down","tired":"Need sleep","title":"Name","today":"This day","total":"Sum","touch":"Feel",
  "tough":"Strong","towel":"Dry off","tower":"Tall building","toxic":"Poisonous","trace":"Follow trail","track":"Race path",
  "trade":"Exchange","trail":"Hiking path","train":"Railway vehicle","trash":"Garbage","treat":"Special reward","trend":"Popular style",
  "trial":"Court case","tribe":"Native group","trick":"Clever act","tried":"Attempted","troop":"Soldier group","truck":"Big vehicle",
  "truly":"Really","trunk":"Tree base","trust":"Have faith","truth":"Not a lie","tumor":"Growth","twice":"Two times",
  "twist":"Turn around","ultra":"Extreme","uncle":"Parent sibling","under":"Below","union":"Workers group","unite":"Join together",
  "unity":"Togetherness","until":"Up to","upper":"Higher part","upset":"Disturbed","urban":"City life","usual":"Normal",
  "valid":"Legitimate","value":"Worth","vault":"Safe room","venue":"Event place","verse":"Poem line","video":"Moving pictures",
  "vigor":"Energy","viral":"Spreading fast","virus":"Makes you sick","visit":"Go see","vital":"Essential","vivid":"Bright colors",
  "vocal":"Using voice","voice":"Speak with it","voter":"Election participant",
  "wagon":"Pull cart","waste":"Throw away","watch":"Look at","water":"H2O","weary":"Very tired","weave":"Make cloth",
  "weird":"Strange","whale":"Ocean giant","wheat":"Bread grain","wheel":"Round roller","where":"What place","which":"What one",
  "while":"During","white":"Snow color","whole":"Complete","whose":"Belonging to who","wider":"More broad","witch":"Magic woman",
  "woman":"Adult female","world":"Earth","worry":"Feel anxious","worse":"More bad","worst":"Most bad","worth":"Value",
  "would":"Might","wound":"Injury","wrist":"Hand joint","write":"Put words down","wrong":"Not right","wrote":"Did write",
  "yacht":"Luxury boat","yield":"Give way","young":"Not old","youth":"Young age","zebra":"Striped animal"
};
